package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class INotStartsWith extends AbstractNonQueryableCondition<String> {

    @PropertyDefinition(validate = "notNull", get="")
    private final IStartsWith iStartsWith;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.INOT_STARTS_WITH);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.iStartsWith(IStartsWith.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value", builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public INotStartsWith(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.INOT_STARTS_WITH, rangeField);
        iStartsWith = new IStartsWith(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new INotStartsWith(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code INotStartsWith}.
     * @return the meta-bean, not null
     */
    public static INotStartsWith.Meta meta() {
        return INotStartsWith.Meta.INSTANCE;
    }

    static {
        MetaBean.register(INotStartsWith.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static INotStartsWith.Builder builder() {
        return new INotStartsWith.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected INotStartsWith(INotStartsWith.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.iStartsWith, "iStartsWith");
        this.iStartsWith = builder.iStartsWith;
    }

    @Override
    public INotStartsWith.Meta metaBean() {
        return INotStartsWith.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            INotStartsWith other = (INotStartsWith) obj;
            return JodaBeanUtils.equal(iStartsWith, other.iStartsWith) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(iStartsWith);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("INotStartsWith{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("iStartsWith").append('=').append(JodaBeanUtils.toString(iStartsWith)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code INotStartsWith}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code iStartsWith} property.
         */
        private final MetaProperty<IStartsWith> iStartsWith = DirectMetaProperty.ofImmutable(
                this, "iStartsWith", INotStartsWith.class, IStartsWith.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "iStartsWith");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 736594432:  // iStartsWith
                    return iStartsWith;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public INotStartsWith.Builder builder() {
            return new INotStartsWith.Builder();
        }

        @Override
        public Class<? extends INotStartsWith> beanType() {
            return INotStartsWith.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code iStartsWith} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<IStartsWith> iStartsWith() {
            return iStartsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 736594432:  // iStartsWith
                    return ((INotStartsWith) bean).iStartsWith;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code INotStartsWith}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private IStartsWith iStartsWith;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(INotStartsWith beanToCopy) {
            super(beanToCopy);
            this.iStartsWith = beanToCopy.iStartsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 736594432:  // iStartsWith
                    return iStartsWith;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 736594432:  // iStartsWith
                    this.iStartsWith = (IStartsWith) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public INotStartsWith build() {
            preBuild(this);
            return new INotStartsWith(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the iStartsWith.
         * @param iStartsWith  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder iStartsWith(IStartsWith iStartsWith) {
            JodaBeanUtils.notNull(iStartsWith, "iStartsWith");
            this.iStartsWith = iStartsWith;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("INotStartsWith.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("iStartsWith").append('=').append(JodaBeanUtils.toString(iStartsWith)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
