package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class IsNull<T> extends SimpleCondition<Object, T> {


    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.IS_NULL);
    }

    public IsNull(String fieldName, boolean rangeField) {
        super(fieldName, Operation.IS_NULL, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new IsNull<>(fieldName, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code IsNull}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static IsNull.Meta meta() {
        return IsNull.Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code IsNull}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> IsNull.Meta<R> metaIsNull(Class<R> cls) {
        return IsNull.Meta.INSTANCE;
    }

    static {
        MetaBean.register(IsNull.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @param <T>  the type
     * @return the builder, not null
     */
    public static <T> IsNull.Builder<T> builder() {
        return new IsNull.Builder<>();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected IsNull(IsNull.Builder<T> builder) {
        super(builder);
    }

    @SuppressWarnings("unchecked")
    @Override
    public IsNull.Meta<T> metaBean() {
        return IsNull.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder<T> toBuilder() {
        return new Builder<>(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(32);
        buf.append("IsNull{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code IsNull}.
     * @param <T>  the type
     */
    public static class Meta<T> extends SimpleCondition.Meta<Object, T> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap());

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public IsNull.Builder<T> builder() {
            return new IsNull.Builder<>();
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends IsNull<T>> beanType() {
            return (Class) IsNull.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code IsNull}.
     * @param <T>  the type
     */
    public static class Builder<T> extends SimpleCondition.Builder<Object, T> {

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(IsNull<T> beanToCopy) {
            super(beanToCopy);
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            return super.get(propertyName);
        }

        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            super.set(propertyName, newValue);
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public IsNull<T> build() {
            return new IsNull<>(this);
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(32);
            buf.append("IsNull.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}

