package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import com.cyoda.core.conditions.queryable.Equals;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class NotEquals extends AbstractNonQueryableCondition<Comparable> {

    @PropertyDefinition(validate = "notNull", get="")
    private final Equals equals;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.NOT_EQUAL);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.equals(Equals.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public NotEquals(String fieldName, Comparable value) {
        this(fieldName, value, false);
    }

    public NotEquals(String fieldName, Comparable value, boolean rangeField) {
        super(fieldName, value, Operation.NOT_EQUAL, rangeField);
        equals = new Equals(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new NotEquals(fieldName, this.value, this.isRangeField());
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code NotEquals}.
     * @return the meta-bean, not null
     */
    public static NotEquals.Meta meta() {
        return NotEquals.Meta.INSTANCE;
    }

    static {
        MetaBean.register(NotEquals.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static NotEquals.Builder builder() {
        return new NotEquals.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected NotEquals(NotEquals.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.equals, "equals");
        this.equals = builder.equals;
    }

    @Override
    public NotEquals.Meta metaBean() {
        return NotEquals.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            NotEquals other = (NotEquals) obj;
            return JodaBeanUtils.equal(equals, other.equals) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(equals);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("NotEquals{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("equals").append('=').append(JodaBeanUtils.toString(equals)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code NotEquals}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<Comparable> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code equals} property.
         */
        private final MetaProperty<Equals> equals = DirectMetaProperty.ofImmutable(
                this, "equals", NotEquals.class, Equals.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "equals");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1295482945:  // equals
                    return equals;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public NotEquals.Builder builder() {
            return new NotEquals.Builder();
        }

        @Override
        public Class<? extends NotEquals> beanType() {
            return NotEquals.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code equals} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Equals> equals() {
            return equals;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1295482945:  // equals
                    return ((NotEquals) bean).equals;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code NotEquals}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<Comparable> {

        private Equals equals;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(NotEquals beanToCopy) {
            super(beanToCopy);
            this.equals = beanToCopy.equals;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1295482945:  // equals
                    return equals;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1295482945:  // equals
                    this.equals = (Equals) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public NotEquals build() {
            preBuild(this);
            return new NotEquals(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the equals.
         * @param equals  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder equals(Equals equals) {
            JodaBeanUtils.notNull(equals, "equals");
            this.equals = equals;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("NotEquals.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("equals").append('=').append(JodaBeanUtils.toString(equals)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
