package com.cyoda.presto.client.treenode.dto.list;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Date;
import java.util.List;
import java.util.Map;

@BeanDefinition
public class EntityListDto implements Bean {
    @PropertyDefinition
    private Date lastTableUpdateTime;
    @PropertyDefinition
    private List<EntityKeyDto> keyList;

    public EntityListDto() {
    }

    public EntityListDto(Date lastTableUpdateTime, List<EntityKeyDto> keyList) {
        this.lastTableUpdateTime = lastTableUpdateTime;
        this.keyList = keyList;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code EntityListDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the lastTableUpdateTime.
     * @return the value of the property
     */
    public Date getLastTableUpdateTime() {
        return lastTableUpdateTime;
    }

    /**
     * Sets the lastTableUpdateTime.
     * @param lastTableUpdateTime  the new value of the property
     */
    public void setLastTableUpdateTime(Date lastTableUpdateTime) {
        this.lastTableUpdateTime = lastTableUpdateTime;
    }

    /**
     * Gets the the {@code lastTableUpdateTime} property.
     * @return the property, not null
     */
    public final Property<Date> lastTableUpdateTime() {
        return metaBean().lastTableUpdateTime().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the keyList.
     * @return the value of the property
     */
    public List<EntityKeyDto> getKeyList() {
        return keyList;
    }

    /**
     * Sets the keyList.
     * @param keyList  the new value of the property
     */
    public void setKeyList(List<EntityKeyDto> keyList) {
        this.keyList = keyList;
    }

    /**
     * Gets the the {@code keyList} property.
     * @return the property, not null
     */
    public final Property<List<EntityKeyDto>> keyList() {
        return metaBean().keyList().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public EntityListDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            EntityListDto other = (EntityListDto) obj;
            return JodaBeanUtils.equal(getLastTableUpdateTime(), other.getLastTableUpdateTime()) &&
                    JodaBeanUtils.equal(getKeyList(), other.getKeyList());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getLastTableUpdateTime());
        hash = hash * 31 + JodaBeanUtils.hashCode(getKeyList());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("EntityListDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("lastTableUpdateTime").append('=').append(JodaBeanUtils.toString(getLastTableUpdateTime())).append(',').append(' ');
        buf.append("keyList").append('=').append(JodaBeanUtils.toString(getKeyList())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code EntityListDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code lastTableUpdateTime} property.
         */
        private final MetaProperty<Date> lastTableUpdateTime = DirectMetaProperty.ofReadWrite(
                this, "lastTableUpdateTime", EntityListDto.class, Date.class);
        /**
         * The meta-property for the {@code keyList} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<EntityKeyDto>> keyList = DirectMetaProperty.ofReadWrite(
                this, "keyList", EntityListDto.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "lastTableUpdateTime",
                "keyList");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1931118638:  // lastTableUpdateTime
                    return lastTableUpdateTime;
                case -815694947:  // keyList
                    return keyList;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends EntityListDto> builder() {
            return new DirectBeanBuilder<>(new EntityListDto());
        }

        @Override
        public Class<? extends EntityListDto> beanType() {
            return EntityListDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code lastTableUpdateTime} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> lastTableUpdateTime() {
            return lastTableUpdateTime;
        }

        /**
         * The meta-property for the {@code keyList} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<EntityKeyDto>> keyList() {
            return keyList;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1931118638:  // lastTableUpdateTime
                    return ((EntityListDto) bean).getLastTableUpdateTime();
                case -815694947:  // keyList
                    return ((EntityListDto) bean).getKeyList();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1931118638:  // lastTableUpdateTime
                    ((EntityListDto) bean).setLastTableUpdateTime((Date) newValue);
                    return;
                case -815694947:  // keyList
                    ((EntityListDto) bean).setKeyList((List<EntityKeyDto>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
