package com.cyoda.presto.client.treenode.dto.list;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Date;
import java.util.Map;
import java.util.UUID;

@BeanDefinition
public class EntityKeyDto implements Bean {
    @PropertyDefinition
    private UUID id;
    @PropertyDefinition
    private Date lastUpdateTime;

    public EntityKeyDto() {
    }

    public EntityKeyDto(UUID id, Date lastUpdateTime) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code EntityKeyDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the id.
     * @return the value of the property
     */
    public UUID getId() {
        return id;
    }

    /**
     * Sets the id.
     * @param id  the new value of the property
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Gets the the {@code id} property.
     * @return the property, not null
     */
    public final Property<UUID> id() {
        return metaBean().id().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the lastUpdateTime.
     * @return the value of the property
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * Sets the lastUpdateTime.
     * @param lastUpdateTime  the new value of the property
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Gets the the {@code lastUpdateTime} property.
     * @return the property, not null
     */
    public final Property<Date> lastUpdateTime() {
        return metaBean().lastUpdateTime().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public EntityKeyDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            EntityKeyDto other = (EntityKeyDto) obj;
            return JodaBeanUtils.equal(getId(), other.getId()) &&
                    JodaBeanUtils.equal(getLastUpdateTime(), other.getLastUpdateTime());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getLastUpdateTime());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("EntityKeyDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("id").append('=').append(JodaBeanUtils.toString(getId())).append(',').append(' ');
        buf.append("lastUpdateTime").append('=').append(JodaBeanUtils.toString(getLastUpdateTime())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code EntityKeyDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code id} property.
         */
        private final MetaProperty<UUID> id = DirectMetaProperty.ofReadWrite(
                this, "id", EntityKeyDto.class, UUID.class);
        /**
         * The meta-property for the {@code lastUpdateTime} property.
         */
        private final MetaProperty<Date> lastUpdateTime = DirectMetaProperty.ofReadWrite(
                this, "lastUpdateTime", EntityKeyDto.class, Date.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "id",
                "lastUpdateTime");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return id;
                case -86827412:  // lastUpdateTime
                    return lastUpdateTime;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends EntityKeyDto> builder() {
            return new DirectBeanBuilder<>(new EntityKeyDto());
        }

        @Override
        public Class<? extends EntityKeyDto> beanType() {
            return EntityKeyDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code id} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<UUID> id() {
            return id;
        }

        /**
         * The meta-property for the {@code lastUpdateTime} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> lastUpdateTime() {
            return lastUpdateTime;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return ((EntityKeyDto) bean).getId();
                case -86827412:  // lastUpdateTime
                    return ((EntityKeyDto) bean).getLastUpdateTime();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    ((EntityKeyDto) bean).setId((UUID) newValue);
                    return;
                case -86827412:  // lastUpdateTime
                    ((EntityKeyDto) bean).setLastUpdateTime((Date) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
