/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.core.util.joda;

import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.function.Supplier;

@BeanDefinition(builderScope = "public")
public abstract class JodaBeansContainer<T> implements ImmutableBean {

    @PropertyDefinition(validate = "notNull")
    private final T data;

    protected JodaBeansContainer(T data) {
        this.data = data;
    }

    public static <X> X getData(JodaBeansContainer<X> blc, Supplier<X> defValSupl) {
        return blc != null ? blc.getData() : defValSupl.get();
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code JodaBeansContainer}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static JodaBeansContainer.Meta meta() {
        return JodaBeansContainer.Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code JodaBeansContainer}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> JodaBeansContainer.Meta<R> metaJodaBeansContainer(Class<R> cls) {
        return JodaBeansContainer.Meta.INSTANCE;
    }

    static {
        MetaBean.register(JodaBeansContainer.Meta.INSTANCE);
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected JodaBeansContainer(JodaBeansContainer.Builder<T> builder) {
        JodaBeanUtils.notNull(builder.data, "data");
        this.data = builder.data;
    }

    @SuppressWarnings("unchecked")
    @Override
    public JodaBeansContainer.Meta<T> metaBean() {
        return JodaBeansContainer.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the data.
     * @return the value of the property, not null
     */
    public T getData() {
        return data;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public abstract Builder<T> toBuilder();

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            JodaBeansContainer<?> other = (JodaBeansContainer<?>) obj;
            return JodaBeanUtils.equal(data, other.data);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(data);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("JodaBeansContainer{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("data").append('=').append(JodaBeanUtils.toString(data)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code JodaBeansContainer}.
     * @param <T>  the type
     */
    public static class Meta<T> extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code data} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<T> data = (DirectMetaProperty) DirectMetaProperty.ofImmutable(
                this, "data", JodaBeansContainer.class, Object.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "data");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    return data;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public boolean isBuildable() {
            return false;
        }

        @Override
        public JodaBeansContainer.Builder<T> builder() {
            throw new UnsupportedOperationException("JodaBeansContainer is an abstract class");
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends JodaBeansContainer<T>> beanType() {
            return (Class) JodaBeansContainer.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code data} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<T> data() {
            return data;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    return ((JodaBeansContainer<?>) bean).getData();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code JodaBeansContainer}.
     * @param <T>  the type
     */
    public abstract static class Builder<T> extends DirectFieldsBeanBuilder<JodaBeansContainer<T>> {

        private T data;

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(JodaBeansContainer<T> beanToCopy) {
            this.data = beanToCopy.getData();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    return data;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    this.data = (T) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the data.
         * @param data  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T> data(T data) {
            JodaBeanUtils.notNull(data, "data");
            this.data = data;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("JodaBeansContainer.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        protected void toString(StringBuilder buf) {
            buf.append("data").append('=').append(JodaBeanUtils.toString(data)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
