package com.cyoda.presto.client.treenode.dto.schema;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
public class FieldConfigDto implements Bean {
    @PropertyDefinition
    private String fieldName; // display; default = fieldKey;
    @PropertyDefinition
    private String fieldKey; // key form <String, String> map
    @PropertyDefinition
    private String dataType;

    public FieldConfigDto() {
    }

    public FieldConfigDto(String fieldName, String fieldKey, String dataType) {
        this.fieldName = fieldName;
        this.fieldKey = fieldKey;
        this.dataType = dataType;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code FieldConfigDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the fieldName.
     * @return the value of the property
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the fieldName.
     * @param fieldName  the new value of the property
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * Gets the the {@code fieldName} property.
     * @return the property, not null
     */
    public final Property<String> fieldName() {
        return metaBean().fieldName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the fieldKey.
     * @return the value of the property
     */
    public String getFieldKey() {
        return fieldKey;
    }

    /**
     * Sets the fieldKey.
     * @param fieldKey  the new value of the property
     */
    public void setFieldKey(String fieldKey) {
        this.fieldKey = fieldKey;
    }

    /**
     * Gets the the {@code fieldKey} property.
     * @return the property, not null
     */
    public final Property<String> fieldKey() {
        return metaBean().fieldKey().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the dataType.
     * @return the value of the property
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the dataType.
     * @param dataType  the new value of the property
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * Gets the the {@code dataType} property.
     * @return the property, not null
     */
    public final Property<String> dataType() {
        return metaBean().dataType().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public FieldConfigDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            FieldConfigDto other = (FieldConfigDto) obj;
            return JodaBeanUtils.equal(getFieldName(), other.getFieldName()) &&
                    JodaBeanUtils.equal(getFieldKey(), other.getFieldKey()) &&
                    JodaBeanUtils.equal(getDataType(), other.getDataType());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getFieldName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getFieldKey());
        hash = hash * 31 + JodaBeanUtils.hashCode(getDataType());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(128);
        buf.append("FieldConfigDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("fieldName").append('=').append(JodaBeanUtils.toString(getFieldName())).append(',').append(' ');
        buf.append("fieldKey").append('=').append(JodaBeanUtils.toString(getFieldKey())).append(',').append(' ');
        buf.append("dataType").append('=').append(JodaBeanUtils.toString(getDataType())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code FieldConfigDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code fieldName} property.
         */
        private final MetaProperty<String> fieldName = DirectMetaProperty.ofReadWrite(
                this, "fieldName", FieldConfigDto.class, String.class);
        /**
         * The meta-property for the {@code fieldKey} property.
         */
        private final MetaProperty<String> fieldKey = DirectMetaProperty.ofReadWrite(
                this, "fieldKey", FieldConfigDto.class, String.class);
        /**
         * The meta-property for the {@code dataType} property.
         */
        private final MetaProperty<String> dataType = DirectMetaProperty.ofReadWrite(
                this, "dataType", FieldConfigDto.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "fieldName",
                "fieldKey",
                "dataType");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    return fieldName;
                case -929027323:  // fieldKey
                    return fieldKey;
                case 1789070852:  // dataType
                    return dataType;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends FieldConfigDto> builder() {
            return new DirectBeanBuilder<>(new FieldConfigDto());
        }

        @Override
        public Class<? extends FieldConfigDto> beanType() {
            return FieldConfigDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code fieldName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> fieldName() {
            return fieldName;
        }

        /**
         * The meta-property for the {@code fieldKey} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> fieldKey() {
            return fieldKey;
        }

        /**
         * The meta-property for the {@code dataType} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> dataType() {
            return dataType;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    return ((FieldConfigDto) bean).getFieldName();
                case -929027323:  // fieldKey
                    return ((FieldConfigDto) bean).getFieldKey();
                case 1789070852:  // dataType
                    return ((FieldConfigDto) bean).getDataType();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    ((FieldConfigDto) bean).setFieldName((String) newValue);
                    return;
                case -929027323:  // fieldKey
                    ((FieldConfigDto) bean).setFieldKey((String) newValue);
                    return;
                case 1789070852:  // dataType
                    ((FieldConfigDto) bean).setDataType((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
