package com.cyoda.presto.client.treenode.dto.schema;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.List;
import java.util.Map;
@BeanDefinition
public class SchemaConfigDto implements Bean {
    @PropertyDefinition
    private String schemaName;

    @PropertyDefinition
    private List<TableConfigDto> tables;

    public SchemaConfigDto() {
    }

    public SchemaConfigDto(String schemaName, List<TableConfigDto> tables) {
        this.schemaName = schemaName;
        this.tables = tables;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code SchemaConfigDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the schemaName.
     * @return the value of the property
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * Sets the schemaName.
     * @param schemaName  the new value of the property
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    /**
     * Gets the the {@code schemaName} property.
     * @return the property, not null
     */
    public final Property<String> schemaName() {
        return metaBean().schemaName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the tables.
     * @return the value of the property
     */
    public List<TableConfigDto> getTables() {
        return tables;
    }

    /**
     * Sets the tables.
     * @param tables  the new value of the property
     */
    public void setTables(List<TableConfigDto> tables) {
        this.tables = tables;
    }

    /**
     * Gets the the {@code tables} property.
     * @return the property, not null
     */
    public final Property<List<TableConfigDto>> tables() {
        return metaBean().tables().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public SchemaConfigDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            SchemaConfigDto other = (SchemaConfigDto) obj;
            return JodaBeanUtils.equal(getSchemaName(), other.getSchemaName()) &&
                    JodaBeanUtils.equal(getTables(), other.getTables());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getSchemaName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getTables());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("SchemaConfigDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("schemaName").append('=').append(JodaBeanUtils.toString(getSchemaName())).append(',').append(' ');
        buf.append("tables").append('=').append(JodaBeanUtils.toString(getTables())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code SchemaConfigDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code schemaName} property.
         */
        private final MetaProperty<String> schemaName = DirectMetaProperty.ofReadWrite(
                this, "schemaName", SchemaConfigDto.class, String.class);
        /**
         * The meta-property for the {@code tables} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<TableConfigDto>> tables = DirectMetaProperty.ofReadWrite(
                this, "tables", SchemaConfigDto.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "schemaName",
                "tables");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -448762932:  // schemaName
                    return schemaName;
                case -881377691:  // tables
                    return tables;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends SchemaConfigDto> builder() {
            return new DirectBeanBuilder<>(new SchemaConfigDto());
        }

        @Override
        public Class<? extends SchemaConfigDto> beanType() {
            return SchemaConfigDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code schemaName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> schemaName() {
            return schemaName;
        }

        /**
         * The meta-property for the {@code tables} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<TableConfigDto>> tables() {
            return tables;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -448762932:  // schemaName
                    return ((SchemaConfigDto) bean).getSchemaName();
                case -881377691:  // tables
                    return ((SchemaConfigDto) bean).getTables();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -448762932:  // schemaName
                    ((SchemaConfigDto) bean).setSchemaName((String) newValue);
                    return;
                case -881377691:  // tables
                    ((SchemaConfigDto) bean).setTables((List<TableConfigDto>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
