package com.cyoda.presto.client.treenode.dto.schema;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@BeanDefinition
public class TableConfigDto implements Bean {
    @PropertyDefinition
    private String tableName; // display; default = entityPartName
    @PropertyDefinition
    private UUID metadataClassId; // link to entityName.partName on cyoda side
    @PropertyDefinition
    private String parentIdName;
    @PropertyDefinition
    private List<FieldConfigDto> fields;

    public TableConfigDto() {
    }

    public TableConfigDto(String tableName, UUID metadataClassId, String parentIdName, List<FieldConfigDto> fields) {
        this.tableName = tableName;
        this.metadataClassId = metadataClassId;
        this.parentIdName = parentIdName;
        this.fields = fields;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code TableConfigDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the tableName.
     * @return the value of the property
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the tableName.
     * @param tableName  the new value of the property
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * Gets the the {@code tableName} property.
     * @return the property, not null
     */
    public final Property<String> tableName() {
        return metaBean().tableName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the metadataClassId.
     * @return the value of the property
     */
    public UUID getMetadataClassId() {
        return metadataClassId;
    }

    /**
     * Sets the metadataClassId.
     * @param metadataClassId  the new value of the property
     */
    public void setMetadataClassId(UUID metadataClassId) {
        this.metadataClassId = metadataClassId;
    }

    /**
     * Gets the the {@code metadataClassId} property.
     * @return the property, not null
     */
    public final Property<UUID> metadataClassId() {
        return metaBean().metadataClassId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the parentIdName.
     * @return the value of the property
     */
    public String getParentIdName() {
        return parentIdName;
    }

    /**
     * Sets the parentIdName.
     * @param parentIdName  the new value of the property
     */
    public void setParentIdName(String parentIdName) {
        this.parentIdName = parentIdName;
    }

    /**
     * Gets the the {@code parentIdName} property.
     * @return the property, not null
     */
    public final Property<String> parentIdName() {
        return metaBean().parentIdName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the fields.
     * @return the value of the property
     */
    public List<FieldConfigDto> getFields() {
        return fields;
    }

    /**
     * Sets the fields.
     * @param fields  the new value of the property
     */
    public void setFields(List<FieldConfigDto> fields) {
        this.fields = fields;
    }

    /**
     * Gets the the {@code fields} property.
     * @return the property, not null
     */
    public final Property<List<FieldConfigDto>> fields() {
        return metaBean().fields().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public TableConfigDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            TableConfigDto other = (TableConfigDto) obj;
            return JodaBeanUtils.equal(getTableName(), other.getTableName()) &&
                    JodaBeanUtils.equal(getMetadataClassId(), other.getMetadataClassId()) &&
                    JodaBeanUtils.equal(getParentIdName(), other.getParentIdName()) &&
                    JodaBeanUtils.equal(getFields(), other.getFields());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getTableName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getMetadataClassId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getParentIdName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getFields());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(160);
        buf.append("TableConfigDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("tableName").append('=').append(JodaBeanUtils.toString(getTableName())).append(',').append(' ');
        buf.append("metadataClassId").append('=').append(JodaBeanUtils.toString(getMetadataClassId())).append(',').append(' ');
        buf.append("parentIdName").append('=').append(JodaBeanUtils.toString(getParentIdName())).append(',').append(' ');
        buf.append("fields").append('=').append(JodaBeanUtils.toString(getFields())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code TableConfigDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code tableName} property.
         */
        private final MetaProperty<String> tableName = DirectMetaProperty.ofReadWrite(
                this, "tableName", TableConfigDto.class, String.class);
        /**
         * The meta-property for the {@code metadataClassId} property.
         */
        private final MetaProperty<UUID> metadataClassId = DirectMetaProperty.ofReadWrite(
                this, "metadataClassId", TableConfigDto.class, UUID.class);
        /**
         * The meta-property for the {@code parentIdName} property.
         */
        private final MetaProperty<String> parentIdName = DirectMetaProperty.ofReadWrite(
                this, "parentIdName", TableConfigDto.class, String.class);
        /**
         * The meta-property for the {@code fields} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<FieldConfigDto>> fields = DirectMetaProperty.ofReadWrite(
                this, "fields", TableConfigDto.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "tableName",
                "metadataClassId",
                "parentIdName",
                "fields");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1988717703:  // tableName
                    return tableName;
                case 926101124:  // metadataClassId
                    return metadataClassId;
                case 761283472:  // parentIdName
                    return parentIdName;
                case -1274708295:  // fields
                    return fields;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends TableConfigDto> builder() {
            return new DirectBeanBuilder<>(new TableConfigDto());
        }

        @Override
        public Class<? extends TableConfigDto> beanType() {
            return TableConfigDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code tableName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> tableName() {
            return tableName;
        }

        /**
         * The meta-property for the {@code metadataClassId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<UUID> metadataClassId() {
            return metadataClassId;
        }

        /**
         * The meta-property for the {@code parentIdName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> parentIdName() {
            return parentIdName;
        }

        /**
         * The meta-property for the {@code fields} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<FieldConfigDto>> fields() {
            return fields;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1988717703:  // tableName
                    return ((TableConfigDto) bean).getTableName();
                case 926101124:  // metadataClassId
                    return ((TableConfigDto) bean).getMetadataClassId();
                case 761283472:  // parentIdName
                    return ((TableConfigDto) bean).getParentIdName();
                case -1274708295:  // fields
                    return ((TableConfigDto) bean).getFields();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1988717703:  // tableName
                    ((TableConfigDto) bean).setTableName((String) newValue);
                    return;
                case 926101124:  // metadataClassId
                    ((TableConfigDto) bean).setMetadataClassId((UUID) newValue);
                    return;
                case 761283472:  // parentIdName
                    ((TableConfigDto) bean).setParentIdName((String) newValue);
                    return;
                case -1274708295:  // fields
                    ((TableConfigDto) bean).setFields((List<FieldConfigDto>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
