package com.cyoda.core.conditions.queryable;

import com.cyoda.core.conditions.BetweenRangeCondition;
import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.RangeExpression;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Collection;
import java.util.Comparator;
import java.util.Map;

import static java.util.Arrays.asList;

/**
 * @author troshanin
 *         Date: 28.07.14
 */
@BeanDefinition(hierarchy = "immutable")
public class BetweenInclusive<T> extends BetweenRangeCondition<T> {

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.BETWEEN_INCLUSIVE);
    }

    public BetweenInclusive(String field, Comparable<T> from, Comparable<T> to, boolean rangeField) {
        super(field, from, to, Operation.BETWEEN_INCLUSIVE, rangeField);
    }

    @Override
    public Collection<RangeExpression> generateRangeExpressions() {
        return asList(new RangeExpression(fieldName, from, RangeExpression.Operator.GREATER_THAN_EQUALS), new RangeExpression(fieldName, to, RangeExpression.Operator.LESS_THAN_EQUALS));
    }

    @Override
    public <S> boolean evaluate(S from, S to, Comparable<S> value, Comparator comparator) {
        if (comparator != null) {
            return comparator.compare(value, from) >= 0 && comparator.compare(value, to) <= 0;
        } else {
            return value.compareTo(from) >= 0 && value.compareTo(to) <= 0;
        }
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new BetweenInclusive<>(fieldName, this.from, this.to, this.isRangeField());
    }

    @Override
    protected String getOperationSign() {
        return "<=";
    }

    @Override
    public String toString() {
        return super.toString();
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code BetweenInclusive}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static BetweenInclusive.Meta meta() {
        return BetweenInclusive.Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code BetweenInclusive}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> BetweenInclusive.Meta<R> metaBetweenInclusive(Class<R> cls) {
        return BetweenInclusive.Meta.INSTANCE;
    }

    static {
        MetaBean.register(BetweenInclusive.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @param <T>  the type
     * @return the builder, not null
     */
    public static <T> BetweenInclusive.Builder<T> builder() {
        return new BetweenInclusive.Builder<>();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected BetweenInclusive(BetweenInclusive.Builder<T> builder) {
        super(builder);
    }

    @SuppressWarnings("unchecked")
    @Override
    public BetweenInclusive.Meta<T> metaBean() {
        return BetweenInclusive.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder<T> toBuilder() {
        return new Builder<>(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code BetweenInclusive}.
     * @param <T>  the type
     */
    public static class Meta<T> extends BetweenRangeCondition.Meta<T> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap());

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public BetweenInclusive.Builder<T> builder() {
            return new BetweenInclusive.Builder<>();
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends BetweenInclusive<T>> beanType() {
            return (Class) BetweenInclusive.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code BetweenInclusive}.
     * @param <T>  the type
     */
    public static class Builder<T> extends BetweenRangeCondition.Builder<T> {

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(BetweenInclusive<T> beanToCopy) {
            super(beanToCopy);
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            return super.get(propertyName);
        }

        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            super.set(propertyName, newValue);
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public BetweenInclusive<T> build() {
            return new BetweenInclusive<>(this);
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(32);
            buf.append("BetweenInclusive.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
