package com.cyoda.core.conditions.queryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.RangeExpression;
import com.cyoda.core.conditions.RangeExpression.Operator;
import com.cyoda.core.conditions.SimpleRangeCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Collection;
import java.util.Collections;
import java.util.Map;

/**
 * @author troshanin
 *         Date: 28.07.14
 */
@BeanDefinition(hierarchy = "immutable")
public final class Equals extends SimpleRangeCondition {

    @PropertyDefinition(get="is")
    private final boolean queryable;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.queryable(true).operation(Operation.EQUALS);
    }

    public Equals(String field, Comparable value) {
        this(field, value, false, true);
    }
    public Equals(String field, Comparable value, boolean rangeField) {
        this(field, value, rangeField, true);
    }

    public Equals(String field, Comparable value, boolean rangeField, boolean queryable) {
        super(field, value, Operation.EQUALS, rangeField);
        this.queryable = queryable;
    }

    @Override
    public Collection<RangeExpression> generateRangeExpressions() {
        return Collections.singletonList(new RangeExpression(fieldName, value, Operator.EQUAL));
    }

    @Override
    public Equals copyWithNewFieldName(String fieldName) {
        return new Equals(fieldName, this.value, this.isRangeField(), this.queryable);
    }

    @Override
    public String toString() {
        return super.toString();
    }

    @Override
    protected String getOperationSign() {
        return "=";
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code Equals}.
     * @return the meta-bean, not null
     */
    public static Equals.Meta meta() {
        return Equals.Meta.INSTANCE;
    }

    static {
        MetaBean.register(Equals.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static Equals.Builder builder() {
        return new Equals.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    private Equals(Equals.Builder builder) {
        super(builder);
        this.queryable = builder.queryable;
    }

    @Override
    public Equals.Meta metaBean() {
        return Equals.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the queryable.
     * @return the value of the property
     */
    public boolean isQueryable() {
        return queryable;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            Equals other = (Equals) obj;
            return (queryable == other.queryable) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(queryable);
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code Equals}.
     */
    public static final class Meta extends SimpleRangeCondition.Meta {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code queryable} property.
         */
        private final MetaProperty<Boolean> queryable = DirectMetaProperty.ofImmutable(
                this, "queryable", Equals.class, Boolean.TYPE);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "queryable");

        /**
         * Restricted constructor.
         */
        private Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1806497246:  // queryable
                    return queryable;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public Equals.Builder builder() {
            return new Equals.Builder();
        }

        @Override
        public Class<? extends Equals> beanType() {
            return Equals.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code queryable} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Boolean> queryable() {
            return queryable;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1806497246:  // queryable
                    return ((Equals) bean).isQueryable();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code Equals}.
     */
    public static final class Builder extends SimpleRangeCondition.Builder {

        private boolean queryable;

        /**
         * Restricted constructor.
         */
        private Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        private Builder(Equals beanToCopy) {
            super(beanToCopy);
            this.queryable = beanToCopy.isQueryable();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1806497246:  // queryable
                    return queryable;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1806497246:  // queryable
                    this.queryable = (Boolean) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public Equals build() {
            return new Equals(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the queryable.
         * @param queryable  the new value
         * @return this, for chaining, not null
         */
        public Builder queryable(boolean queryable) {
            this.queryable = queryable;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("Equals.Builder{");
            buf.append("queryable").append('=').append(JodaBeanUtils.toString(queryable));
            buf.append('}');
            return buf.toString();
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
