package com.cyoda.core.conditions.queryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.RangeExpression;
import com.cyoda.core.conditions.SimpleCondition;
import com.cyoda.core.conditions.SimpleRangeCondition;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Collection;
import java.util.Collections;
import java.util.Map;

/**
 * @author troshanin
 *         Date: 28.07.14
 */
@BeanDefinition(hierarchy = "immutable")
public class GreaterThan extends SimpleRangeCondition {

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.GREATER_THAN);
    }

    public GreaterThan(String field, Comparable value, boolean rangeField) {
        super(field, value, Operation.GREATER_THAN, rangeField);
    }

    @Override
    public Collection<RangeExpression> generateRangeExpressions() {
        return Collections.singletonList(new RangeExpression(fieldName, value, RangeExpression.Operator.GREATER));
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new GreaterThan(fieldName, this.value, this.isRangeField());
    }

    @Override
    public String toString() {
        return super.toString();
    }

    @Override
    protected String getOperationSign() {
        return ">";
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code GreaterThan}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected GreaterThan(Builder builder) {
        super(builder);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code GreaterThan}.
     */
    public static class Meta extends SimpleRangeCondition.Meta {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap());

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public Builder builder() {
            return new Builder();
        }

        @Override
        public Class<? extends GreaterThan> beanType() {
            return GreaterThan.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code GreaterThan}.
     */
    public static class Builder extends SimpleRangeCondition.Builder {

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(GreaterThan beanToCopy) {
            super(beanToCopy);
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            return super.get(propertyName);
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            super.set(propertyName, newValue);
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public GreaterThan build() {
            return new GreaterThan(this);
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(32);
            buf.append("GreaterThan.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
