package com.cyoda.core.conditions.queryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.RangeCondition;
import com.cyoda.core.conditions.RangeExpression;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.springframework.util.StringUtils;

import javax.validation.constraints.NotNull;
import java.util.Collection;
import java.util.Collections;
import java.util.Map;

import static java.util.Arrays.asList;

/**
 * Compares two Strings character by character lexicographically based on a dictionary or natural ordering.
 * For Cassandra that means check that column value is equals or greater than {@link StartsWith#value}(the searching String)
 * and less than {@link StartsWith#valueTo} (String where the last character is changed to the next character by the natural ordering.))
 * Start with 'ab' means 'ab' >= column value < 'ac'.
 * Following values will be found: 'ab', 'abcd', 'ab1234' etc.
 */
@BeanDefinition(hierarchy = "immutable")
public class StartsWith extends RangeCondition<Object, String> {

    @PropertyDefinition(validate = "notNull")
    protected final String value;

    @PropertyDefinition(validate = "notNull")
    protected final String valueTo;

    public StartsWith(String fieldName, String value, boolean rangeField) {
        super(fieldName, Operation.STARTS_WITH, rangeField);
        this.value = value != null ? value : "";
        this.valueTo = calculateTo(this.value);
    }

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.STARTS_WITH);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        builder.valueTo(calculateTo(builder.value));
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new StartsWith(fieldName, value, this.isRangeField());
    }

    protected static String calculateTo(@NotNull String from){
        if (from.isEmpty()) {
            return "";
        }
        char[] chars = from.toCharArray();
        chars[chars.length - 1]++;
        return new String(chars);
    }

    @Override
    public Collection<RangeExpression> generateRangeExpressions() {
        if (StringUtils.hasLength(valueTo)) {
            return asList(new RangeExpression(fieldName, value, RangeExpression.Operator.GREATER_THAN_EQUALS), new RangeExpression(fieldName, valueTo, RangeExpression.Operator.LESS));
        } else {
            return Collections.singletonList(new RangeExpression(fieldName, value, RangeExpression.Operator.GREATER_THAN_EQUALS));
        }
    }

    public boolean evaluateSimple(String columnValue){
        return columnValue != null && columnValue.startsWith(value);
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
    }

    @Override
    public String toString() {
        return super.toString();
    }

    @Override
    protected String getOperationSign() {
        return ">=";
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code StartsWith}.
     * @return the meta-bean, not null
     */
    public static StartsWith.Meta meta() {
        return StartsWith.Meta.INSTANCE;
    }

    static {
        MetaBean.register(StartsWith.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static StartsWith.Builder builder() {
        return new StartsWith.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected StartsWith(StartsWith.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.value, "value");
        JodaBeanUtils.notNull(builder.valueTo, "valueTo");
        this.value = builder.value;
        this.valueTo = builder.valueTo;
    }

    @Override
    public StartsWith.Meta metaBean() {
        return StartsWith.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the value.
     * @return the value of the property, not null
     */
    public String getValue() {
        return value;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the valueTo.
     * @return the value of the property, not null
     */
    public String getValueTo() {
        return valueTo;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            StartsWith other = (StartsWith) obj;
            return JodaBeanUtils.equal(value, other.value) &&
                    JodaBeanUtils.equal(valueTo, other.valueTo) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(value);
        hash = hash * 31 + JodaBeanUtils.hashCode(valueTo);
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code StartsWith}.
     */
    public static class Meta extends RangeCondition.Meta<Object, String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code value} property.
         */
        private final MetaProperty<String> value = DirectMetaProperty.ofImmutable(
                this, "value", StartsWith.class, String.class);
        /**
         * The meta-property for the {@code valueTo} property.
         */
        private final MetaProperty<String> valueTo = DirectMetaProperty.ofImmutable(
                this, "valueTo", StartsWith.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "value",
                "valueTo");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return value;
                case 231605196:  // valueTo
                    return valueTo;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public StartsWith.Builder builder() {
            return new StartsWith.Builder();
        }

        @Override
        public Class<? extends StartsWith> beanType() {
            return StartsWith.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code value} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> value() {
            return value;
        }

        /**
         * The meta-property for the {@code valueTo} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> valueTo() {
            return valueTo;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return ((StartsWith) bean).getValue();
                case 231605196:  // valueTo
                    return ((StartsWith) bean).getValueTo();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code StartsWith}.
     */
    public static class Builder extends RangeCondition.Builder<Object, String> {

        private String value;
        private String valueTo;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(StartsWith beanToCopy) {
            super(beanToCopy);
            this.value = beanToCopy.getValue();
            this.valueTo = beanToCopy.getValueTo();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return value;
                case 231605196:  // valueTo
                    return valueTo;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    this.value = (String) newValue;
                    break;
                case 231605196:  // valueTo
                    this.valueTo = (String) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public StartsWith build() {
            preBuild(this);
            return new StartsWith(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the value.
         * @param value  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder value(String value) {
            JodaBeanUtils.notNull(value, "value");
            this.value = value;
            return this;
        }

        /**
         * Sets the valueTo.
         * @param valueTo  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder valueTo(String valueTo) {
            JodaBeanUtils.notNull(valueTo, "valueTo");
            this.valueTo = valueTo;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(96);
            buf.append("StartsWith.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("value").append('=').append(JodaBeanUtils.toString(value)).append(',').append(' ');
            buf.append("valueTo").append('=').append(JodaBeanUtils.toString(valueTo)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
