package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

/**
 * @author troshanin
 *         Date: 28.07.14
 */
@BeanDefinition(hierarchy = "immutable")
public abstract class AbstractNonQueryableCondition<T> extends SimpleCondition<Object, T> {

    @PropertyDefinition(validate = "notNull")
    protected final T value;

    protected AbstractNonQueryableCondition(String fieldName, T value, Operation operation, boolean rangeField) {
        super(fieldName, operation, rangeField);

        this.value = value;
    }

    @Override
    public String toString() {
        final String superStr = super.toString();
        return superStr.substring(0, superStr.length() - 1) +
                ", value=" + value +
                '}';
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code AbstractNonQueryableCondition}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static AbstractNonQueryableCondition.Meta meta() {
        return AbstractNonQueryableCondition.Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code AbstractNonQueryableCondition}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> AbstractNonQueryableCondition.Meta<R> metaAbstractNonQueryableCondition(Class<R> cls) {
        return AbstractNonQueryableCondition.Meta.INSTANCE;
    }

    static {
        MetaBean.register(AbstractNonQueryableCondition.Meta.INSTANCE);
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected AbstractNonQueryableCondition(AbstractNonQueryableCondition.Builder<T> builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.value, "value");
        this.value = builder.value;
    }

    @SuppressWarnings("unchecked")
    @Override
    public AbstractNonQueryableCondition.Meta<T> metaBean() {
        return AbstractNonQueryableCondition.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the value.
     * @return the value of the property, not null
     */
    public T getValue() {
        return value;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public abstract Builder<T> toBuilder();

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            AbstractNonQueryableCondition<?> other = (AbstractNonQueryableCondition<?>) obj;
            return JodaBeanUtils.equal(value, other.value) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(value);
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code AbstractNonQueryableCondition}.
     * @param <T>  the type
     */
    public static class Meta<T> extends SimpleCondition.Meta<Object, T> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code value} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<T> value = (DirectMetaProperty) DirectMetaProperty.ofImmutable(
                this, "value", AbstractNonQueryableCondition.class, Object.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "value");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return value;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public boolean isBuildable() {
            return false;
        }

        @Override
        public AbstractNonQueryableCondition.Builder<T> builder() {
            throw new UnsupportedOperationException("AbstractNonQueryableCondition is an abstract class");
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends AbstractNonQueryableCondition<T>> beanType() {
            return (Class) AbstractNonQueryableCondition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code value} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<T> value() {
            return value;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return ((AbstractNonQueryableCondition<?>) bean).getValue();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code AbstractNonQueryableCondition}.
     * @param <T>  the type
     */
    public abstract static class Builder<T> extends SimpleCondition.Builder<Object, T> {

        private T value;

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(AbstractNonQueryableCondition<T> beanToCopy) {
            super(beanToCopy);
            this.value = beanToCopy.getValue();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    return value;
                default:
                    return super.get(propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 111972721:  // value
                    this.value = (T) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the value.
         * @param value  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T> value(T value) {
            JodaBeanUtils.notNull(value, "value");
            this.value = value;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("AbstractNonQueryableCondition.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("value").append('=').append(JodaBeanUtils.toString(value)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
