package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import com.google.common.collect.ImmutableSet;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;
import java.util.Set;

/**
 * None understandable class...
 *
 * It checks that the specified Comparable value and field value of some Entity have same attributes.
 *
 * Example:
 * there is class with next structure
 * class TestEntity {
 *     MyClass myClass;
 * }
 * and
 * class MyClass {
 *     String param1;
 *     String param2;
 *     String param3;
 * }
 *
 * So we can create new EqualByAttributes object where we will pass:
 * <pre>{@code
 * field: 'myClass'
 * value: new MyClass(param1Val, param2Val)
 * attrsToCheck: Set<String>('param1', 'param3')
 *
 * So when we will execute evaluate method, we will take columnsValue and value,
 * then from each MyClass object we'll take param1 & param3 values and then compare them.
 * if value.param1 == colValue.param1 && value.param3 == colValue.param3
 * then returning true
 * else - false
 * }</pre>
 *
 * @author troshanin
 *         Date: 19.06.15
 */
@BeanDefinition(hierarchy = "immutable")
public class EqualByAttributes extends AbstractNonQueryableCondition<Comparable> {

    @PropertyDefinition(validate = "notNull", get="")
    private final Set<String> attrsToCheck;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.EQUAL_BY_ATTRIBUTES);
    }

    public EqualByAttributes(String fieldName, Comparable value, Set<String> attrsToCheck) {
        super(fieldName, value, Operation.EQUAL_BY_ATTRIBUTES, false);
        this.attrsToCheck = attrsToCheck;
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new EqualByAttributes(fieldName, value, attrsToCheck);
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code EqualByAttributes}.
     * @return the meta-bean, not null
     */
    public static EqualByAttributes.Meta meta() {
        return EqualByAttributes.Meta.INSTANCE;
    }

    static {
        MetaBean.register(EqualByAttributes.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static EqualByAttributes.Builder builder() {
        return new EqualByAttributes.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected EqualByAttributes(EqualByAttributes.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.attrsToCheck, "attrsToCheck");
        this.attrsToCheck = ImmutableSet.copyOf(builder.attrsToCheck);
    }

    @Override
    public EqualByAttributes.Meta metaBean() {
        return EqualByAttributes.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            EqualByAttributes other = (EqualByAttributes) obj;
            return JodaBeanUtils.equal(attrsToCheck, other.attrsToCheck) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(attrsToCheck);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("EqualByAttributes{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("attrsToCheck").append('=').append(JodaBeanUtils.toString(attrsToCheck)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code EqualByAttributes}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<Comparable> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code attrsToCheck} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Set<String>> attrsToCheck = DirectMetaProperty.ofImmutable(
                this, "attrsToCheck", EqualByAttributes.class, (Class) Set.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "attrsToCheck");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -525413301:  // attrsToCheck
                    return attrsToCheck;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public EqualByAttributes.Builder builder() {
            return new EqualByAttributes.Builder();
        }

        @Override
        public Class<? extends EqualByAttributes> beanType() {
            return EqualByAttributes.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code attrsToCheck} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Set<String>> attrsToCheck() {
            return attrsToCheck;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -525413301:  // attrsToCheck
                    return ((EqualByAttributes) bean).attrsToCheck;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code EqualByAttributes}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<Comparable> {

        private Set<String> attrsToCheck = ImmutableSet.of();

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(EqualByAttributes beanToCopy) {
            super(beanToCopy);
            this.attrsToCheck = ImmutableSet.copyOf(beanToCopy.attrsToCheck);
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -525413301:  // attrsToCheck
                    return attrsToCheck;
                default:
                    return super.get(propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -525413301:  // attrsToCheck
                    this.attrsToCheck = (Set<String>) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public EqualByAttributes build() {
            return new EqualByAttributes(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the attrsToCheck.
         * @param attrsToCheck  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder attrsToCheck(Set<String> attrsToCheck) {
            JodaBeanUtils.notNull(attrsToCheck, "attrsToCheck");
            this.attrsToCheck = attrsToCheck;
            return this;
        }

        /**
         * Sets the {@code attrsToCheck} property in the builder
         * from an array of objects.
         * @param attrsToCheck  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder attrsToCheck(String... attrsToCheck) {
            return attrsToCheck(ImmutableSet.copyOf(attrsToCheck));
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("EqualByAttributes.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("attrsToCheck").append('=').append(JodaBeanUtils.toString(attrsToCheck)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
