package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class INotEndsWith extends AbstractNonQueryableCondition<String> {

    @PropertyDefinition(validate = "notNull", get="")
    private final IEndsWith iEndsWith;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.INOT_ENDS_WITH);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.iEndsWith(IEndsWith.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }
    public INotEndsWith(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.INOT_ENDS_WITH, rangeField);
        iEndsWith = new IEndsWith(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new INotEndsWith(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code INotEndsWith}.
     * @return the meta-bean, not null
     */
    public static INotEndsWith.Meta meta() {
        return INotEndsWith.Meta.INSTANCE;
    }

    static {
        MetaBean.register(INotEndsWith.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static INotEndsWith.Builder builder() {
        return new INotEndsWith.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected INotEndsWith(INotEndsWith.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.iEndsWith, "iEndsWith");
        this.iEndsWith = builder.iEndsWith;
    }

    @Override
    public INotEndsWith.Meta metaBean() {
        return INotEndsWith.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            INotEndsWith other = (INotEndsWith) obj;
            return JodaBeanUtils.equal(iEndsWith, other.iEndsWith) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(iEndsWith);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("INotEndsWith{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("iEndsWith").append('=').append(JodaBeanUtils.toString(iEndsWith)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code INotEndsWith}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code iEndsWith} property.
         */
        private final MetaProperty<IEndsWith> iEndsWith = DirectMetaProperty.ofImmutable(
                this, "iEndsWith", INotEndsWith.class, IEndsWith.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "iEndsWith");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1003644775:  // iEndsWith
                    return iEndsWith;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public INotEndsWith.Builder builder() {
            return new INotEndsWith.Builder();
        }

        @Override
        public Class<? extends INotEndsWith> beanType() {
            return INotEndsWith.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code iEndsWith} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<IEndsWith> iEndsWith() {
            return iEndsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1003644775:  // iEndsWith
                    return ((INotEndsWith) bean).iEndsWith;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code INotEndsWith}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private IEndsWith iEndsWith;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(INotEndsWith beanToCopy) {
            super(beanToCopy);
            this.iEndsWith = beanToCopy.iEndsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1003644775:  // iEndsWith
                    return iEndsWith;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 1003644775:  // iEndsWith
                    this.iEndsWith = (IEndsWith) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public INotEndsWith build() {
            preBuild(this);
            return new INotEndsWith(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the iEndsWith.
         * @param iEndsWith  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder iEndsWith(IEndsWith iEndsWith) {
            JodaBeanUtils.notNull(iEndsWith, "iEndsWith");
            this.iEndsWith = iEndsWith;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("INotEndsWith.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("iEndsWith").append('=').append(JodaBeanUtils.toString(iEndsWith)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
