package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class INotEquals  extends AbstractNonQueryableCondition<String> {

    @PropertyDefinition(validate = "notNull", get="")
    private final IEquals iEquals;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.INOT_EQUAL);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.iEquals(IEquals.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public INotEquals(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.INOT_EQUAL, rangeField);
        iEquals = new IEquals(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new INotEquals(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code INotEquals}.
     * @return the meta-bean, not null
     */
    public static INotEquals.Meta meta() {
        return INotEquals.Meta.INSTANCE;
    }

    static {
        MetaBean.register(INotEquals.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static INotEquals.Builder builder() {
        return new INotEquals.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected INotEquals(INotEquals.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.iEquals, "iEquals");
        this.iEquals = builder.iEquals;
    }

    @Override
    public INotEquals.Meta metaBean() {
        return INotEquals.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            INotEquals other = (INotEquals) obj;
            return JodaBeanUtils.equal(iEquals, other.iEquals) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(iEquals);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("INotEquals{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("iEquals").append('=').append(JodaBeanUtils.toString(iEquals)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code INotEquals}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code iEquals} property.
         */
        private final MetaProperty<IEquals> iEquals = DirectMetaProperty.ofImmutable(
                this, "iEquals", INotEquals.class, IEquals.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "iEquals");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 781957512:  // iEquals
                    return iEquals;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public INotEquals.Builder builder() {
            return new INotEquals.Builder();
        }

        @Override
        public Class<? extends INotEquals> beanType() {
            return INotEquals.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code iEquals} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<IEquals> iEquals() {
            return iEquals;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 781957512:  // iEquals
                    return ((INotEquals) bean).iEquals;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code INotEquals}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private IEquals iEquals;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(INotEquals beanToCopy) {
            super(beanToCopy);
            this.iEquals = beanToCopy.iEquals;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 781957512:  // iEquals
                    return iEquals;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 781957512:  // iEquals
                    this.iEquals = (IEquals) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public INotEquals build() {
            preBuild(this);
            return new INotEquals(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the iEquals.
         * @param iEquals  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder iEquals(IEquals iEquals) {
            JodaBeanUtils.notNull(iEquals, "iEquals");
            this.iEquals = iEquals;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("INotEquals.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("iEquals").append('=').append(JodaBeanUtils.toString(iEquals)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
