package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

/**
 * @author troshanin
 *         Date: 28.07.14
 */
@BeanDefinition(hierarchy = "immutable")
public class INotContains extends AbstractNonQueryableCondition<String> {

    @PropertyDefinition(validate = "notNull", get="")
    private final IContains icontains;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.INOT_CONTAINS);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.icontains(IContains.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }


    public INotContains(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.INOT_CONTAINS, rangeField);
        icontains = new IContains(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new INotContains(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code INotContains}.
     * @return the meta-bean, not null
     */
    public static INotContains.Meta meta() {
        return INotContains.Meta.INSTANCE;
    }

    static {
        MetaBean.register(INotContains.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static INotContains.Builder builder() {
        return new INotContains.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected INotContains(INotContains.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.icontains, "icontains");
        this.icontains = builder.icontains;
    }

    @Override
    public INotContains.Meta metaBean() {
        return INotContains.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            INotContains other = (INotContains) obj;
            return JodaBeanUtils.equal(icontains, other.icontains) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(icontains);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("INotContains{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("icontains").append('=').append(JodaBeanUtils.toString(icontains)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code INotContains}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code icontains} property.
         */
        private final MetaProperty<IContains> icontains = DirectMetaProperty.ofImmutable(
                this, "icontains", INotContains.class, IContains.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "icontains");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1371603576:  // icontains
                    return icontains;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public INotContains.Builder builder() {
            return new INotContains.Builder();
        }

        @Override
        public Class<? extends INotContains> beanType() {
            return INotContains.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code icontains} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<IContains> icontains() {
            return icontains;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1371603576:  // icontains
                    return ((INotContains) bean).icontains;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code INotContains}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private IContains icontains;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(INotContains beanToCopy) {
            super(beanToCopy);
            this.icontains = beanToCopy.icontains;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1371603576:  // icontains
                    return icontains;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1371603576:  // icontains
                    this.icontains = (IContains) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public INotContains build() {
            preBuild(this);
            return new INotContains(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the icontains.
         * @param icontains  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder icontains(IContains icontains) {
            JodaBeanUtils.notNull(icontains, "icontains");
            this.icontains = icontains;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("INotContains.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("icontains").append('=').append(JodaBeanUtils.toString(icontains)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
