package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class NotEndsWith extends AbstractNonQueryableCondition<String>{

    @PropertyDefinition(validate = "notNull", get="")
    private final EndsWith endsWith;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.NOT_ENDS_WITH);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.endsWith(EndsWith.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public NotEndsWith(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.NOT_ENDS_WITH, rangeField);
        endsWith = new EndsWith(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new NotEndsWith(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code NotEndsWith}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected NotEndsWith(Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.endsWith, "endsWith");
        this.endsWith = builder.endsWith;
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            NotEndsWith other = (NotEndsWith) obj;
            return JodaBeanUtils.equal(endsWith, other.endsWith) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(endsWith);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("NotEndsWith{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("endsWith").append('=').append(JodaBeanUtils.toString(endsWith)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code NotEndsWith}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code endsWith} property.
         */
        private final MetaProperty<EndsWith> endsWith = DirectMetaProperty.ofImmutable(
                this, "endsWith", NotEndsWith.class, EndsWith.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "endsWith");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1743158238:  // endsWith
                    return endsWith;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public Builder builder() {
            return new Builder();
        }

        @Override
        public Class<? extends NotEndsWith> beanType() {
            return NotEndsWith.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code endsWith} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<EndsWith> endsWith() {
            return endsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1743158238:  // endsWith
                    return ((NotEndsWith) bean).endsWith;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code NotEndsWith}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private EndsWith endsWith;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(NotEndsWith beanToCopy) {
            super(beanToCopy);
            this.endsWith = beanToCopy.endsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1743158238:  // endsWith
                    return endsWith;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 1743158238:  // endsWith
                    this.endsWith = (EndsWith) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public NotEndsWith build() {
            preBuild(this);
            return new NotEndsWith(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the endsWith.
         * @param endsWith  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder endsWith(EndsWith endsWith) {
            JodaBeanUtils.notNull(endsWith, "endsWith");
            this.endsWith = endsWith;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("NotEndsWith.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("endsWith").append('=').append(JodaBeanUtils.toString(endsWith)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
