package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class NotNull<T> extends SimpleCondition<Object, T>{

    @PropertyDefinition(validate = "notNull", get="")
    private final IsNull<T> isNull;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.NOT_NULL);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.isNull(IsNull.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public NotNull(String fieldName, boolean rangeField) {
        super(fieldName, Operation.NOT_NULL, rangeField);
        isNull = new IsNull<>(fieldName, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new NotNull<>(fieldName, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code NotNull}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code NotNull}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> Meta<R> metaNotNull(Class<R> cls) {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @param <T>  the type
     * @return the builder, not null
     */
    public static <T> Builder<T> builder() {
        return new Builder<>();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected NotNull(Builder<T> builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.isNull, "isNull");
        this.isNull = builder.isNull;
    }

    @SuppressWarnings("unchecked")
    @Override
    public Meta<T> metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder<T> toBuilder() {
        return new Builder<>(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            NotNull<?> other = (NotNull<?>) obj;
            return JodaBeanUtils.equal(isNull, other.isNull) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(isNull);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("NotNull{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("isNull").append('=').append(JodaBeanUtils.toString(isNull)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code NotNull}.
     * @param <T>  the type
     */
    public static class Meta<T> extends SimpleCondition.Meta<Object, T> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code isNull} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<IsNull<T>> isNull = DirectMetaProperty.ofImmutable(
                this, "isNull", NotNull.class, (Class) IsNull.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "isNull");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1180261935:  // isNull
                    return isNull;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public Builder<T> builder() {
            return new Builder<>();
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends NotNull<T>> beanType() {
            return (Class) NotNull.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code isNull} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<IsNull<T>> isNull() {
            return isNull;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1180261935:  // isNull
                    return ((NotNull<?>) bean).isNull;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code NotNull}.
     * @param <T>  the type
     */
    public static class Builder<T> extends SimpleCondition.Builder<Object, T> {

        private IsNull<T> isNull;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(NotNull<T> beanToCopy) {
            super(beanToCopy);
            this.isNull = beanToCopy.isNull;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1180261935:  // isNull
                    return isNull;
                default:
                    return super.get(propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1180261935:  // isNull
                    this.isNull = (IsNull<T>) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public NotNull<T> build() {
            preBuild(this);
            return new NotNull<>(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the isNull.
         * @param isNull  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T> isNull(IsNull<T> isNull) {
            JodaBeanUtils.notNull(isNull, "isNull");
            this.isNull = isNull;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("NotNull.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("isNull").append('=').append(JodaBeanUtils.toString(isNull)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
