package com.cyoda.core.conditions.nonqueryable;

import com.cyoda.core.conditions.Operation;
import com.cyoda.core.conditions.SimpleCondition;
import com.cyoda.core.conditions.queryable.StartsWith;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.ImmutablePreBuild;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public class NotStartsWith extends AbstractNonQueryableCondition<String> {

    @PropertyDefinition(validate = "notNull", get="")
    private final StartsWith startsWith;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.operation(Operation.NOT_STARTS_WITH);
    }

    @ImmutablePreBuild
    private static void preBuild(Builder builder) {
        // TODO: Figure out how to access the superclass fields of the builder. Probably need an enhancement of joda beans?
        builder.startsWith(StartsWith.builder()
                .set("fieldName",builder.get("fieldName"))
                .set("value",builder.get("value"))
                .set("rangeField",builder.get("rangeField"))
                .build()
        );
    }

    public NotStartsWith(String fieldName, String value, boolean rangeField) {
        super(fieldName, value, Operation.NOT_STARTS_WITH, rangeField);
        startsWith = new StartsWith(fieldName, value, rangeField);
    }

    @Override
    public SimpleCondition copyWithNewFieldName(String fieldName) {
        return new NotStartsWith(fieldName, this.value, this.isRangeField());
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code NotStartsWith}.
     * @return the meta-bean, not null
     */
    public static NotStartsWith.Meta meta() {
        return NotStartsWith.Meta.INSTANCE;
    }

    static {
        MetaBean.register(NotStartsWith.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static NotStartsWith.Builder builder() {
        return new NotStartsWith.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected NotStartsWith(NotStartsWith.Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.startsWith, "startsWith");
        this.startsWith = builder.startsWith;
    }

    @Override
    public NotStartsWith.Meta metaBean() {
        return NotStartsWith.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            NotStartsWith other = (NotStartsWith) obj;
            return JodaBeanUtils.equal(startsWith, other.startsWith) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(startsWith);
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("NotStartsWith{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("startsWith").append('=').append(JodaBeanUtils.toString(startsWith)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code NotStartsWith}.
     */
    public static class Meta extends AbstractNonQueryableCondition.Meta<String> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code startsWith} property.
         */
        private final MetaProperty<StartsWith> startsWith = DirectMetaProperty.ofImmutable(
                this, "startsWith", NotStartsWith.class, StartsWith.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "startsWith");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1555538761:  // startsWith
                    return startsWith;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public NotStartsWith.Builder builder() {
            return new NotStartsWith.Builder();
        }

        @Override
        public Class<? extends NotStartsWith> beanType() {
            return NotStartsWith.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code startsWith} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<StartsWith> startsWith() {
            return startsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1555538761:  // startsWith
                    return ((NotStartsWith) bean).startsWith;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code NotStartsWith}.
     */
    public static class Builder extends AbstractNonQueryableCondition.Builder<String> {

        private StartsWith startsWith;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(NotStartsWith beanToCopy) {
            super(beanToCopy);
            this.startsWith = beanToCopy.startsWith;
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1555538761:  // startsWith
                    return startsWith;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1555538761:  // startsWith
                    this.startsWith = (StartsWith) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public NotStartsWith build() {
            preBuild(this);
            return new NotStartsWith(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the startsWith.
         * @param startsWith  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder startsWith(StartsWith startsWith) {
            JodaBeanUtils.notNull(startsWith, "startsWith");
            this.startsWith = startsWith;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("NotStartsWith.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("startsWith").append('=').append(JodaBeanUtils.toString(startsWith)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
