/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.service.api.beans;

import com.cyoda.core.reports.columns.Function;
import com.cyoda.core.reports.columns.ReportColumn;
import com.cyoda.core.reports.columns.ReportSortColumn;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.KeyDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.beans.ConstructorProperties;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;

/**
 * Created by: paul
 * Created on: 20.02.16
 */
@BeanDefinition(constructorScope = "public@ConstructorProperties")
public final class ReportDefinition implements ImmutableBean {

    @JsonProperty
    @PropertyDefinition
    private final String description;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final String requestClass;

    @JsonProperty
    @PropertyDefinition()
    private final Map<String,Object> condition;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final Date pointTime;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final Date valuationPointTime;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final List<ReportColumn> columns;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final List<ReportSortColumn> sorting;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final List<ReportColumn> grouping;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    @JsonDeserialize(keyUsing = ReportDefinition.ReportColumnDeserializer.class)
    private final Map<ReportColumn, List<Function>> summary;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final List<Map<String,Object>> colDefs;

    @JsonProperty(required = true)
    @PropertyDefinition(validate = "notNull")
    private final List<Map<String,Object>> aliasDefs;

    @JsonProperty
    @PropertyDefinition
    private final boolean hierarhyEnable;

    @JsonProperty
    @PropertyDefinition
    private final int reportVersion;

    public static class ReportColumnDeserializer extends KeyDeserializer {
        @Override
        public Object deserializeKey(String key, DeserializationContext ctxt) throws IOException {
            return null;
        }
    }


    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ReportDefinition}.
     * @return the meta-bean, not null
     */
    public static ReportDefinition.Meta meta() {
        return ReportDefinition.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ReportDefinition.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static ReportDefinition.Builder builder() {
        return new ReportDefinition.Builder();
    }

    /**
     * Creates an instance.
     * @param description  the value of the property
     * @param requestClass  the value of the property, not null
     * @param condition  the value of the property
     * @param pointTime  the value of the property, not null
     * @param valuationPointTime  the value of the property, not null
     * @param columns  the value of the property, not null
     * @param sorting  the value of the property, not null
     * @param grouping  the value of the property, not null
     * @param summary  the value of the property, not null
     * @param colDefs  the value of the property, not null
     * @param aliasDefs  the value of the property, not null
     * @param hierarhyEnable  the value of the property
     * @param reportVersion  the value of the property
     */
    @ConstructorProperties({"description", "requestClass", "condition", "pointTime", "valuationPointTime", "columns", "sorting", "grouping", "summary", "colDefs", "aliasDefs", "hierarhyEnable", "reportVersion"})
    public ReportDefinition(
            String description,
            String requestClass,
            Map<String,Object> condition,
            Date pointTime,
            Date valuationPointTime,
            List<ReportColumn> columns,
            List<ReportSortColumn> sorting,
            List<ReportColumn> grouping,
            Map<ReportColumn, List<Function>> summary,
            List<Map<String,Object>> colDefs,
            List<Map<String,Object>> aliasDefs,
            boolean hierarhyEnable,
            int reportVersion) {
        JodaBeanUtils.notNull(requestClass, "requestClass");
        JodaBeanUtils.notNull(pointTime, "pointTime");
        JodaBeanUtils.notNull(valuationPointTime, "valuationPointTime");
        JodaBeanUtils.notNull(columns, "columns");
        JodaBeanUtils.notNull(sorting, "sorting");
        JodaBeanUtils.notNull(grouping, "grouping");
        JodaBeanUtils.notNull(summary, "summary");
        JodaBeanUtils.notNull(colDefs, "colDefs");
        JodaBeanUtils.notNull(aliasDefs, "aliasDefs");
        this.description = description;
        this.requestClass = requestClass;
        this.condition = (condition != null ? ImmutableMap.copyOf(condition) : null);
        this.pointTime = (Date) pointTime.clone();
        this.valuationPointTime = (Date) valuationPointTime.clone();
        this.columns = ImmutableList.copyOf(columns);
        this.sorting = ImmutableList.copyOf(sorting);
        this.grouping = ImmutableList.copyOf(grouping);
        this.summary = ImmutableMap.copyOf(summary);
        this.colDefs = ImmutableList.copyOf(colDefs);
        this.aliasDefs = ImmutableList.copyOf(aliasDefs);
        this.hierarhyEnable = hierarhyEnable;
        this.reportVersion = reportVersion;
    }

    @Override
    public ReportDefinition.Meta metaBean() {
        return ReportDefinition.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the description.
     * @return the value of the property
     */
    public String getDescription() {
        return description;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the requestClass.
     * @return the value of the property, not null
     */
    public String getRequestClass() {
        return requestClass;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the condition.
     * @return the value of the property
     */
    public Map<String,Object> getCondition() {
        return condition;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the pointTime.
     * @return the value of the property, not null
     */
    public Date getPointTime() {
        return (Date) pointTime.clone();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the valuationPointTime.
     * @return the value of the property, not null
     */
    public Date getValuationPointTime() {
        return (Date) valuationPointTime.clone();
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the columns.
     * @return the value of the property, not null
     */
    public List<ReportColumn> getColumns() {
        return columns;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the sorting.
     * @return the value of the property, not null
     */
    public List<ReportSortColumn> getSorting() {
        return sorting;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the grouping.
     * @return the value of the property, not null
     */
    public List<ReportColumn> getGrouping() {
        return grouping;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the summary.
     * @return the value of the property, not null
     */
    public Map<ReportColumn, List<Function>> getSummary() {
        return summary;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the colDefs.
     * @return the value of the property, not null
     */
    public List<Map<String,Object>> getColDefs() {
        return colDefs;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the aliasDefs.
     * @return the value of the property, not null
     */
    public List<Map<String,Object>> getAliasDefs() {
        return aliasDefs;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the hierarhyEnable.
     * @return the value of the property
     */
    public boolean isHierarhyEnable() {
        return hierarhyEnable;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the reportVersion.
     * @return the value of the property
     */
    public int getReportVersion() {
        return reportVersion;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ReportDefinition other = (ReportDefinition) obj;
            return JodaBeanUtils.equal(description, other.description) &&
                    JodaBeanUtils.equal(requestClass, other.requestClass) &&
                    JodaBeanUtils.equal(condition, other.condition) &&
                    JodaBeanUtils.equal(pointTime, other.pointTime) &&
                    JodaBeanUtils.equal(valuationPointTime, other.valuationPointTime) &&
                    JodaBeanUtils.equal(columns, other.columns) &&
                    JodaBeanUtils.equal(sorting, other.sorting) &&
                    JodaBeanUtils.equal(grouping, other.grouping) &&
                    JodaBeanUtils.equal(summary, other.summary) &&
                    JodaBeanUtils.equal(colDefs, other.colDefs) &&
                    JodaBeanUtils.equal(aliasDefs, other.aliasDefs) &&
                    (hierarhyEnable == other.hierarhyEnable) &&
                    (reportVersion == other.reportVersion);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(description);
        hash = hash * 31 + JodaBeanUtils.hashCode(requestClass);
        hash = hash * 31 + JodaBeanUtils.hashCode(condition);
        hash = hash * 31 + JodaBeanUtils.hashCode(pointTime);
        hash = hash * 31 + JodaBeanUtils.hashCode(valuationPointTime);
        hash = hash * 31 + JodaBeanUtils.hashCode(columns);
        hash = hash * 31 + JodaBeanUtils.hashCode(sorting);
        hash = hash * 31 + JodaBeanUtils.hashCode(grouping);
        hash = hash * 31 + JodaBeanUtils.hashCode(summary);
        hash = hash * 31 + JodaBeanUtils.hashCode(colDefs);
        hash = hash * 31 + JodaBeanUtils.hashCode(aliasDefs);
        hash = hash * 31 + JodaBeanUtils.hashCode(hierarhyEnable);
        hash = hash * 31 + JodaBeanUtils.hashCode(reportVersion);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(448);
        buf.append("ReportDefinition{");
        buf.append("description").append('=').append(JodaBeanUtils.toString(description)).append(',').append(' ');
        buf.append("requestClass").append('=').append(JodaBeanUtils.toString(requestClass)).append(',').append(' ');
        buf.append("condition").append('=').append(JodaBeanUtils.toString(condition)).append(',').append(' ');
        buf.append("pointTime").append('=').append(JodaBeanUtils.toString(pointTime)).append(',').append(' ');
        buf.append("valuationPointTime").append('=').append(JodaBeanUtils.toString(valuationPointTime)).append(',').append(' ');
        buf.append("columns").append('=').append(JodaBeanUtils.toString(columns)).append(',').append(' ');
        buf.append("sorting").append('=').append(JodaBeanUtils.toString(sorting)).append(',').append(' ');
        buf.append("grouping").append('=').append(JodaBeanUtils.toString(grouping)).append(',').append(' ');
        buf.append("summary").append('=').append(JodaBeanUtils.toString(summary)).append(',').append(' ');
        buf.append("colDefs").append('=').append(JodaBeanUtils.toString(colDefs)).append(',').append(' ');
        buf.append("aliasDefs").append('=').append(JodaBeanUtils.toString(aliasDefs)).append(',').append(' ');
        buf.append("hierarhyEnable").append('=').append(JodaBeanUtils.toString(hierarhyEnable)).append(',').append(' ');
        buf.append("reportVersion").append('=').append(JodaBeanUtils.toString(reportVersion));
        buf.append('}');
        return buf.toString();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ReportDefinition}.
     */
    public static final class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code description} property.
         */
        private final MetaProperty<String> description = DirectMetaProperty.ofImmutable(
                this, "description", ReportDefinition.class, String.class);
        /**
         * The meta-property for the {@code requestClass} property.
         */
        private final MetaProperty<String> requestClass = DirectMetaProperty.ofImmutable(
                this, "requestClass", ReportDefinition.class, String.class);
        /**
         * The meta-property for the {@code condition} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<String,Object>> condition = DirectMetaProperty.ofImmutable(
                this, "condition", ReportDefinition.class, (Class) Map.class);
        /**
         * The meta-property for the {@code pointTime} property.
         */
        private final MetaProperty<Date> pointTime = DirectMetaProperty.ofImmutable(
                this, "pointTime", ReportDefinition.class, Date.class);
        /**
         * The meta-property for the {@code valuationPointTime} property.
         */
        private final MetaProperty<Date> valuationPointTime = DirectMetaProperty.ofImmutable(
                this, "valuationPointTime", ReportDefinition.class, Date.class);
        /**
         * The meta-property for the {@code columns} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<ReportColumn>> columns = DirectMetaProperty.ofImmutable(
                this, "columns", ReportDefinition.class, (Class) List.class);
        /**
         * The meta-property for the {@code sorting} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<ReportSortColumn>> sorting = DirectMetaProperty.ofImmutable(
                this, "sorting", ReportDefinition.class, (Class) List.class);
        /**
         * The meta-property for the {@code grouping} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<ReportColumn>> grouping = DirectMetaProperty.ofImmutable(
                this, "grouping", ReportDefinition.class, (Class) List.class);
        /**
         * The meta-property for the {@code summary} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<ReportColumn, List<Function>>> summary = DirectMetaProperty.ofImmutable(
                this, "summary", ReportDefinition.class, (Class) Map.class);
        /**
         * The meta-property for the {@code colDefs} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<Map<String,Object>>> colDefs = DirectMetaProperty.ofImmutable(
                this, "colDefs", ReportDefinition.class, (Class) List.class);
        /**
         * The meta-property for the {@code aliasDefs} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<Map<String,Object>>> aliasDefs = DirectMetaProperty.ofImmutable(
                this, "aliasDefs", ReportDefinition.class, (Class) List.class);
        /**
         * The meta-property for the {@code hierarhyEnable} property.
         */
        private final MetaProperty<Boolean> hierarhyEnable = DirectMetaProperty.ofImmutable(
                this, "hierarhyEnable", ReportDefinition.class, Boolean.TYPE);
        /**
         * The meta-property for the {@code reportVersion} property.
         */
        private final MetaProperty<Integer> reportVersion = DirectMetaProperty.ofImmutable(
                this, "reportVersion", ReportDefinition.class, Integer.TYPE);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "description",
                "requestClass",
                "condition",
                "pointTime",
                "valuationPointTime",
                "columns",
                "sorting",
                "grouping",
                "summary",
                "colDefs",
                "aliasDefs",
                "hierarhyEnable",
                "reportVersion");

        /**
         * Restricted constructor.
         */
        private Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1724546052:  // description
                    return description;
                case 1277167657:  // requestClass
                    return requestClass;
                case -861311717:  // condition
                    return condition;
                case 1564529789:  // pointTime
                    return pointTime;
                case -1843609732:  // valuationPointTime
                    return valuationPointTime;
                case 949721053:  // columns
                    return columns;
                case -2024581756:  // sorting
                    return sorting;
                case 506371331:  // grouping
                    return grouping;
                case -1857640538:  // summary
                    return summary;
                case 948253358:  // colDefs
                    return colDefs;
                case 1599496062:  // aliasDefs
                    return aliasDefs;
                case 861472019:  // hierarhyEnable
                    return hierarhyEnable;
                case -536552188:  // reportVersion
                    return reportVersion;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public ReportDefinition.Builder builder() {
            return new ReportDefinition.Builder();
        }

        @Override
        public Class<? extends ReportDefinition> beanType() {
            return ReportDefinition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code description} property.
         * @return the meta-property, not null
         */
        public MetaProperty<String> description() {
            return description;
        }

        /**
         * The meta-property for the {@code requestClass} property.
         * @return the meta-property, not null
         */
        public MetaProperty<String> requestClass() {
            return requestClass;
        }

        /**
         * The meta-property for the {@code condition} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Map<String,Object>> condition() {
            return condition;
        }

        /**
         * The meta-property for the {@code pointTime} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Date> pointTime() {
            return pointTime;
        }

        /**
         * The meta-property for the {@code valuationPointTime} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Date> valuationPointTime() {
            return valuationPointTime;
        }

        /**
         * The meta-property for the {@code columns} property.
         * @return the meta-property, not null
         */
        public MetaProperty<List<ReportColumn>> columns() {
            return columns;
        }

        /**
         * The meta-property for the {@code sorting} property.
         * @return the meta-property, not null
         */
        public MetaProperty<List<ReportSortColumn>> sorting() {
            return sorting;
        }

        /**
         * The meta-property for the {@code grouping} property.
         * @return the meta-property, not null
         */
        public MetaProperty<List<ReportColumn>> grouping() {
            return grouping;
        }

        /**
         * The meta-property for the {@code summary} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Map<ReportColumn, List<Function>>> summary() {
            return summary;
        }

        /**
         * The meta-property for the {@code colDefs} property.
         * @return the meta-property, not null
         */
        public MetaProperty<List<Map<String,Object>>> colDefs() {
            return colDefs;
        }

        /**
         * The meta-property for the {@code aliasDefs} property.
         * @return the meta-property, not null
         */
        public MetaProperty<List<Map<String,Object>>> aliasDefs() {
            return aliasDefs;
        }

        /**
         * The meta-property for the {@code hierarhyEnable} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Boolean> hierarhyEnable() {
            return hierarhyEnable;
        }

        /**
         * The meta-property for the {@code reportVersion} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Integer> reportVersion() {
            return reportVersion;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1724546052:  // description
                    return ((ReportDefinition) bean).getDescription();
                case 1277167657:  // requestClass
                    return ((ReportDefinition) bean).getRequestClass();
                case -861311717:  // condition
                    return ((ReportDefinition) bean).getCondition();
                case 1564529789:  // pointTime
                    return ((ReportDefinition) bean).getPointTime();
                case -1843609732:  // valuationPointTime
                    return ((ReportDefinition) bean).getValuationPointTime();
                case 949721053:  // columns
                    return ((ReportDefinition) bean).getColumns();
                case -2024581756:  // sorting
                    return ((ReportDefinition) bean).getSorting();
                case 506371331:  // grouping
                    return ((ReportDefinition) bean).getGrouping();
                case -1857640538:  // summary
                    return ((ReportDefinition) bean).getSummary();
                case 948253358:  // colDefs
                    return ((ReportDefinition) bean).getColDefs();
                case 1599496062:  // aliasDefs
                    return ((ReportDefinition) bean).getAliasDefs();
                case 861472019:  // hierarhyEnable
                    return ((ReportDefinition) bean).isHierarhyEnable();
                case -536552188:  // reportVersion
                    return ((ReportDefinition) bean).getReportVersion();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code ReportDefinition}.
     */
    public static final class Builder extends DirectFieldsBeanBuilder<ReportDefinition> {

        private String description;
        private String requestClass;
        private Map<String,Object> condition;
        private Date pointTime;
        private Date valuationPointTime;
        private List<ReportColumn> columns = ImmutableList.of();
        private List<ReportSortColumn> sorting = ImmutableList.of();
        private List<ReportColumn> grouping = ImmutableList.of();
        private Map<ReportColumn, List<Function>> summary = ImmutableMap.of();
        private List<Map<String,Object>> colDefs = ImmutableList.of();
        private List<Map<String,Object>> aliasDefs = ImmutableList.of();
        private boolean hierarhyEnable;
        private int reportVersion;

        /**
         * Restricted constructor.
         */
        private Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        private Builder(ReportDefinition beanToCopy) {
            this.description = beanToCopy.getDescription();
            this.requestClass = beanToCopy.getRequestClass();
            this.condition = (beanToCopy.getCondition() != null ? ImmutableMap.copyOf(beanToCopy.getCondition()) : null);
            this.pointTime = (Date) beanToCopy.getPointTime().clone();
            this.valuationPointTime = (Date) beanToCopy.getValuationPointTime().clone();
            this.columns = ImmutableList.copyOf(beanToCopy.getColumns());
            this.sorting = ImmutableList.copyOf(beanToCopy.getSorting());
            this.grouping = ImmutableList.copyOf(beanToCopy.getGrouping());
            this.summary = ImmutableMap.copyOf(beanToCopy.getSummary());
            this.colDefs = ImmutableList.copyOf(beanToCopy.getColDefs());
            this.aliasDefs = ImmutableList.copyOf(beanToCopy.getAliasDefs());
            this.hierarhyEnable = beanToCopy.isHierarhyEnable();
            this.reportVersion = beanToCopy.getReportVersion();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1724546052:  // description
                    return description;
                case 1277167657:  // requestClass
                    return requestClass;
                case -861311717:  // condition
                    return condition;
                case 1564529789:  // pointTime
                    return pointTime;
                case -1843609732:  // valuationPointTime
                    return valuationPointTime;
                case 949721053:  // columns
                    return columns;
                case -2024581756:  // sorting
                    return sorting;
                case 506371331:  // grouping
                    return grouping;
                case -1857640538:  // summary
                    return summary;
                case 948253358:  // colDefs
                    return colDefs;
                case 1599496062:  // aliasDefs
                    return aliasDefs;
                case 861472019:  // hierarhyEnable
                    return hierarhyEnable;
                case -536552188:  // reportVersion
                    return reportVersion;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1724546052:  // description
                    this.description = (String) newValue;
                    break;
                case 1277167657:  // requestClass
                    this.requestClass = (String) newValue;
                    break;
                case -861311717:  // condition
                    this.condition = (Map<String,Object>) newValue;
                    break;
                case 1564529789:  // pointTime
                    this.pointTime = (Date) newValue;
                    break;
                case -1843609732:  // valuationPointTime
                    this.valuationPointTime = (Date) newValue;
                    break;
                case 949721053:  // columns
                    this.columns = (List<ReportColumn>) newValue;
                    break;
                case -2024581756:  // sorting
                    this.sorting = (List<ReportSortColumn>) newValue;
                    break;
                case 506371331:  // grouping
                    this.grouping = (List<ReportColumn>) newValue;
                    break;
                case -1857640538:  // summary
                    this.summary = (Map<ReportColumn, List<Function>>) newValue;
                    break;
                case 948253358:  // colDefs
                    this.colDefs = (List<Map<String,Object>>) newValue;
                    break;
                case 1599496062:  // aliasDefs
                    this.aliasDefs = (List<Map<String,Object>>) newValue;
                    break;
                case 861472019:  // hierarhyEnable
                    this.hierarhyEnable = (Boolean) newValue;
                    break;
                case -536552188:  // reportVersion
                    this.reportVersion = (Integer) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public ReportDefinition build() {
            return new ReportDefinition(
                    description,
                    requestClass,
                    condition,
                    pointTime,
                    valuationPointTime,
                    columns,
                    sorting,
                    grouping,
                    summary,
                    colDefs,
                    aliasDefs,
                    hierarhyEnable,
                    reportVersion);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the description.
         * @param description  the new value
         * @return this, for chaining, not null
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets the requestClass.
         * @param requestClass  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder requestClass(String requestClass) {
            JodaBeanUtils.notNull(requestClass, "requestClass");
            this.requestClass = requestClass;
            return this;
        }

        /**
         * Sets the condition.
         * @param condition  the new value
         * @return this, for chaining, not null
         */
        public Builder condition(Map<String,Object> condition) {
            this.condition = condition;
            return this;
        }

        /**
         * Sets the pointTime.
         * @param pointTime  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder pointTime(Date pointTime) {
            JodaBeanUtils.notNull(pointTime, "pointTime");
            this.pointTime = pointTime;
            return this;
        }

        /**
         * Sets the valuationPointTime.
         * @param valuationPointTime  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder valuationPointTime(Date valuationPointTime) {
            JodaBeanUtils.notNull(valuationPointTime, "valuationPointTime");
            this.valuationPointTime = valuationPointTime;
            return this;
        }

        /**
         * Sets the columns.
         * @param columns  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder columns(List<ReportColumn> columns) {
            JodaBeanUtils.notNull(columns, "columns");
            this.columns = columns;
            return this;
        }

        /**
         * Sets the {@code columns} property in the builder
         * from an array of objects.
         * @param columns  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder columns(ReportColumn... columns) {
            return columns(ImmutableList.copyOf(columns));
        }

        /**
         * Sets the sorting.
         * @param sorting  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder sorting(List<ReportSortColumn> sorting) {
            JodaBeanUtils.notNull(sorting, "sorting");
            this.sorting = sorting;
            return this;
        }

        /**
         * Sets the {@code sorting} property in the builder
         * from an array of objects.
         * @param sorting  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder sorting(ReportSortColumn... sorting) {
            return sorting(ImmutableList.copyOf(sorting));
        }

        /**
         * Sets the grouping.
         * @param grouping  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder grouping(List<ReportColumn> grouping) {
            JodaBeanUtils.notNull(grouping, "grouping");
            this.grouping = grouping;
            return this;
        }

        /**
         * Sets the {@code grouping} property in the builder
         * from an array of objects.
         * @param grouping  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder grouping(ReportColumn... grouping) {
            return grouping(ImmutableList.copyOf(grouping));
        }

        /**
         * Sets the summary.
         * @param summary  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder summary(Map<ReportColumn, List<Function>> summary) {
            JodaBeanUtils.notNull(summary, "summary");
            this.summary = summary;
            return this;
        }

        /**
         * Sets the colDefs.
         * @param colDefs  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder colDefs(List<Map<String,Object>> colDefs) {
            JodaBeanUtils.notNull(colDefs, "colDefs");
            this.colDefs = colDefs;
            return this;
        }

        /**
         * Sets the {@code colDefs} property in the builder
         * from an array of objects.
         * @param colDefs  the new value, not null
         * @return this, for chaining, not null
         */
        @SafeVarargs
        public final Builder colDefs(Map<String,Object>... colDefs) {
            return colDefs(ImmutableList.copyOf(colDefs));
        }

        /**
         * Sets the aliasDefs.
         * @param aliasDefs  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder aliasDefs(List<Map<String,Object>> aliasDefs) {
            JodaBeanUtils.notNull(aliasDefs, "aliasDefs");
            this.aliasDefs = aliasDefs;
            return this;
        }

        /**
         * Sets the {@code aliasDefs} property in the builder
         * from an array of objects.
         * @param aliasDefs  the new value, not null
         * @return this, for chaining, not null
         */
        @SafeVarargs
        public final Builder aliasDefs(Map<String,Object>... aliasDefs) {
            return aliasDefs(ImmutableList.copyOf(aliasDefs));
        }

        /**
         * Sets the hierarhyEnable.
         * @param hierarhyEnable  the new value
         * @return this, for chaining, not null
         */
        public Builder hierarhyEnable(boolean hierarhyEnable) {
            this.hierarhyEnable = hierarhyEnable;
            return this;
        }

        /**
         * Sets the reportVersion.
         * @param reportVersion  the new value
         * @return this, for chaining, not null
         */
        public Builder reportVersion(int reportVersion) {
            this.reportVersion = reportVersion;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(448);
            buf.append("ReportDefinition.Builder{");
            buf.append("description").append('=').append(JodaBeanUtils.toString(description)).append(',').append(' ');
            buf.append("requestClass").append('=').append(JodaBeanUtils.toString(requestClass)).append(',').append(' ');
            buf.append("condition").append('=').append(JodaBeanUtils.toString(condition)).append(',').append(' ');
            buf.append("pointTime").append('=').append(JodaBeanUtils.toString(pointTime)).append(',').append(' ');
            buf.append("valuationPointTime").append('=').append(JodaBeanUtils.toString(valuationPointTime)).append(',').append(' ');
            buf.append("columns").append('=').append(JodaBeanUtils.toString(columns)).append(',').append(' ');
            buf.append("sorting").append('=').append(JodaBeanUtils.toString(sorting)).append(',').append(' ');
            buf.append("grouping").append('=').append(JodaBeanUtils.toString(grouping)).append(',').append(' ');
            buf.append("summary").append('=').append(JodaBeanUtils.toString(summary)).append(',').append(' ');
            buf.append("colDefs").append('=').append(JodaBeanUtils.toString(colDefs)).append(',').append(' ');
            buf.append("aliasDefs").append('=').append(JodaBeanUtils.toString(aliasDefs)).append(',').append(' ');
            buf.append("hierarhyEnable").append('=').append(JodaBeanUtils.toString(hierarhyEnable)).append(',').append(' ');
            buf.append("reportVersion").append('=').append(JodaBeanUtils.toString(reportVersion));
            buf.append('}');
            return buf.toString();
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
