/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.cyoda.service.api.beans;

import com.cyoda.core.reports.columns.Function;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.text.NumberFormat;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Created by Anton
 * on 30/09/16.
 */
@BeanDefinition
public class Summary implements Bean{

    @JsonProperty
    @PropertyDefinition(get = "field", validate = "notNull")
    public final Map<Function, Object> values = new EnumMap<>(Function.class);

    public String asString() {
        final List<String> collect = values.keySet().stream().map(this::formattedSummary).collect(Collectors.toList());
        return String.join(", ", collect);
    }

    private String formattedSummary(Function f) {
        final Object value = values.get(f);
        NumberFormat formatter = NumberFormat.getNumberInstance(java.util.Locale.US);
        String asString = formatter.format(value);

        return f + " = " + asString;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code Summary}.
     * @return the meta-bean, not null
     */
    public static Summary.Meta meta() {
        return Summary.Meta.INSTANCE;
    }

    static {
        MetaBean.register(Summary.Meta.INSTANCE);
    }

    @Override
    public Summary.Meta metaBean() {
        return Summary.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the values.
     * @param values  the new value of the property, not null
     */
    public void setValues(Map<Function, Object> values) {
        JodaBeanUtils.notNull(values, "values");
        this.values.clear();
        this.values.putAll(values);
    }

    /**
     * Gets the the {@code values} property.
     * @return the property, not null
     */
    public final Property<Map<Function, Object>> values() {
        return metaBean().values().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public Summary clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            Summary other = (Summary) obj;
            return JodaBeanUtils.equal(values, other.values);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(values);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("Summary{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("values").append('=').append(JodaBeanUtils.toString(values)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code Summary}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code values} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<Function, Object>> values = DirectMetaProperty.ofReadWrite(
                this, "values", Summary.class, (Class) Map.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "values");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -823812830:  // values
                    return values;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends Summary> builder() {
            return new DirectBeanBuilder<>(new Summary());
        }

        @Override
        public Class<? extends Summary> beanType() {
            return Summary.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code values} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Map<Function, Object>> values() {
            return values;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -823812830:  // values
                    return ((Summary) bean).values;
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -823812830:  // values
                    ((Summary) bean).setValues((Map<Function, Object>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

        @Override
        protected void validate(Bean bean) {
            JodaBeanUtils.notNull(((Summary) bean).values, "values");
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
