/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.core.reports.columndefs;

import com.google.common.collect.ImmutableMap;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;


@BeanDefinition
public class ReportColDef implements Bean {

    @PropertyDefinition
    private String fullPath;
    @PropertyDefinition
    private ReportColPartDef[] parts;

    public ReportColDef() {
    }

    public ReportColDef(String fullPath, ReportColPartDef[] parts) {
        this.fullPath = fullPath;
        this.parts = parts;
    }

    public boolean withRelatedObjects() {
        return parts != null && parts.length > 1;
    }

    public boolean startsWith(ReportColDef other) {
        if (this.parts.length <= other.parts.length){
            return false;
        }
        for (int i = 0; i < other.parts.length; i++) {
            if (!this.parts[i].equals(other.parts[i])) {
                return false;
            }
        }
        return true;
    }

    // TODO: This comes from com.cyoda.core.util.Util.
    public static final Map<Class<?>, Class<?>> PRIMITIVE_TYPES = ImmutableMap.<Class<?>, Class<?>>builder()
            .put(boolean.class, Boolean.class)
            .put(byte.class, Byte.class)
            .put(short.class, Short.class)
            .put(char.class, Character.class)
            .put(int.class, Integer.class)
            .put(long.class, Long.class)
            .put(float.class, Float.class)
            .put(double.class, Double.class)
            .build();

    // TODO: This comes from com.cyoda.core.util.Util.
    public static Class<?> getNonePrimitiveClass(Class<?> clazz) {
        Class<?> clazz0 = PRIMITIVE_TYPES.get(clazz);
        return clazz0 != null ? clazz0 : clazz;
    }

    public ReportColPartDef lastPart() {
        return parts != null ? parts[parts.length - 1] : null;
    }

    public ReportColPartDef firstPart() {
        return parts != null ? parts[0] : null;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ReportColDef}.
     * @return the meta-bean, not null
     */
    public static ReportColDef.Meta meta() {
        return ReportColDef.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ReportColDef.Meta.INSTANCE);
    }

    @Override
    public ReportColDef.Meta metaBean() {
        return ReportColDef.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the fullPath.
     * @return the value of the property
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * Sets the fullPath.
     * @param fullPath  the new value of the property
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath;
    }

    /**
     * Gets the the {@code fullPath} property.
     * @return the property, not null
     */
    public final Property<String> fullPath() {
        return metaBean().fullPath().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the parts.
     * @return the value of the property
     */
    public ReportColPartDef[] getParts() {
        return parts;
    }

    /**
     * Sets the parts.
     * @param parts  the new value of the property
     */
    public void setParts(ReportColPartDef[] parts) {
        this.parts = parts;
    }

    /**
     * Gets the the {@code parts} property.
     * @return the property, not null
     */
    public final Property<ReportColPartDef[]> parts() {
        return metaBean().parts().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public ReportColDef clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ReportColDef other = (ReportColDef) obj;
            return JodaBeanUtils.equal(getFullPath(), other.getFullPath()) &&
                    JodaBeanUtils.equal(getParts(), other.getParts());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getFullPath());
        hash = hash * 31 + JodaBeanUtils.hashCode(getParts());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("ReportColDef{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("fullPath").append('=').append(JodaBeanUtils.toString(getFullPath())).append(',').append(' ');
        buf.append("parts").append('=').append(JodaBeanUtils.toString(getParts())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ReportColDef}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code fullPath} property.
         */
        private final MetaProperty<String> fullPath = DirectMetaProperty.ofReadWrite(
                this, "fullPath", ReportColDef.class, String.class);
        /**
         * The meta-property for the {@code parts} property.
         */
        private final MetaProperty<ReportColPartDef[]> parts = DirectMetaProperty.ofReadWrite(
                this, "parts", ReportColDef.class, ReportColPartDef[].class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "fullPath",
                "parts");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1330912084:  // fullPath
                    return fullPath;
                case 106437344:  // parts
                    return parts;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends ReportColDef> builder() {
            return new DirectBeanBuilder<>(new ReportColDef());
        }

        @Override
        public Class<? extends ReportColDef> beanType() {
            return ReportColDef.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code fullPath} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> fullPath() {
            return fullPath;
        }

        /**
         * The meta-property for the {@code parts} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<ReportColPartDef[]> parts() {
            return parts;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1330912084:  // fullPath
                    return ((ReportColDef) bean).getFullPath();
                case 106437344:  // parts
                    return ((ReportColDef) bean).getParts();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1330912084:  // fullPath
                    ((ReportColDef) bean).setFullPath((String) newValue);
                    return;
                case 106437344:  // parts
                    ((ReportColDef) bean).setParts((ReportColPartDef[]) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
