/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.core.reports.columndefs;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;

@BeanDefinition
public class ReportColPartDef implements Bean {

    @PropertyDefinition
    private String rootClass;
    @PropertyDefinition
    private String path;
    @PropertyDefinition
    private String type;

    public ReportColPartDef() {
    }

    public ReportColPartDef(String rootClass, String path, String type) {
        this.rootClass = rootClass;
        this.path = path;
        this.type = type;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ReportColPartDef}.
     * @return the meta-bean, not null
     */
    public static ReportColPartDef.Meta meta() {
        return ReportColPartDef.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ReportColPartDef.Meta.INSTANCE);
    }

    @Override
    public ReportColPartDef.Meta metaBean() {
        return ReportColPartDef.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the rootClass.
     * @return the value of the property
     */
    public String getRootClass() {
        return rootClass;
    }

    /**
     * Sets the rootClass.
     * @param rootClass  the new value of the property
     */
    public void setRootClass(String rootClass) {
        this.rootClass = rootClass;
    }

    /**
     * Gets the the {@code rootClass} property.
     * @return the property, not null
     */
    public final Property<String> rootClass() {
        return metaBean().rootClass().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the path.
     * @return the value of the property
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the path.
     * @param path  the new value of the property
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Gets the the {@code path} property.
     * @return the property, not null
     */
    public final Property<String> path() {
        return metaBean().path().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the type.
     * @return the value of the property
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type.
     * @param type  the new value of the property
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets the the {@code type} property.
     * @return the property, not null
     */
    public final Property<String> type() {
        return metaBean().type().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public ReportColPartDef clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ReportColPartDef other = (ReportColPartDef) obj;
            return JodaBeanUtils.equal(getRootClass(), other.getRootClass()) &&
                    JodaBeanUtils.equal(getPath(), other.getPath()) &&
                    JodaBeanUtils.equal(getType(), other.getType());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getRootClass());
        hash = hash * 31 + JodaBeanUtils.hashCode(getPath());
        hash = hash * 31 + JodaBeanUtils.hashCode(getType());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(128);
        buf.append("ReportColPartDef{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("rootClass").append('=').append(JodaBeanUtils.toString(getRootClass())).append(',').append(' ');
        buf.append("path").append('=').append(JodaBeanUtils.toString(getPath())).append(',').append(' ');
        buf.append("type").append('=').append(JodaBeanUtils.toString(getType())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ReportColPartDef}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code rootClass} property.
         */
        private final MetaProperty<String> rootClass = DirectMetaProperty.ofReadWrite(
                this, "rootClass", ReportColPartDef.class, String.class);
        /**
         * The meta-property for the {@code path} property.
         */
        private final MetaProperty<String> path = DirectMetaProperty.ofReadWrite(
                this, "path", ReportColPartDef.class, String.class);
        /**
         * The meta-property for the {@code type} property.
         */
        private final MetaProperty<String> type = DirectMetaProperty.ofReadWrite(
                this, "type", ReportColPartDef.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "rootClass",
                "path",
                "type");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -893094474:  // rootClass
                    return rootClass;
                case 3433509:  // path
                    return path;
                case 3575610:  // type
                    return type;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends ReportColPartDef> builder() {
            return new DirectBeanBuilder<>(new ReportColPartDef());
        }

        @Override
        public Class<? extends ReportColPartDef> beanType() {
            return ReportColPartDef.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code rootClass} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> rootClass() {
            return rootClass;
        }

        /**
         * The meta-property for the {@code path} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> path() {
            return path;
        }

        /**
         * The meta-property for the {@code type} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> type() {
            return type;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -893094474:  // rootClass
                    return ((ReportColPartDef) bean).getRootClass();
                case 3433509:  // path
                    return ((ReportColPartDef) bean).getPath();
                case 3575610:  // type
                    return ((ReportColPartDef) bean).getType();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -893094474:  // rootClass
                    ((ReportColPartDef) bean).setRootClass((String) newValue);
                    return;
                case 3433509:  // path
                    ((ReportColPartDef) bean).setPath((String) newValue);
                    return;
                case 3575610:  // type
                    ((ReportColPartDef) bean).setType((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
