#
# Copyright (C) 2022 Cyoda Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# suppress inspection "UnusedProperty" for whole file
connector.name=cyoda
cyoda.presto.schema-name=reporting

cyoda.presto.server.url=http://localhost:8082
cyoda.presto.authentication.type=JWT
cyoda.presto.https-override=true
cyoda.presto.request-page-size=100
cyoda.presto.user-login-endpoint=/api/auth/login
cyoda.presto.refresh-token-endpoint=/api/auth/token

# Only for dev/test!
# This has a perpetual refresh token, that can be generated via JwtTokenFactoryTest#createPerpetualRefreshToken in cyoda platform project.
cyoda.presto.allow-anonymous-login=true
cyoda.presto.anonymous-user-id=000186c8-0000-1000-8080-808080808080
cyoda.presto.anonymous-refresh-token=eyJraWQiOiJiNWE2YTY3Zi1mYWM4LTRlZmUtODk4ZC1mMzRjNWFlOTE0ZjMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwYXVsLnNjaGxlZ2VyQGN5b2RhLmNvbSIsInVzZXJJZCI6IjAwMDE4NmM4LTAwMDAtMTAwMC04MDgwLTgwODA4MDgwODA4MCIsInNjb3BlcyI6WyJST0xFX1JFRlJFU0hfVE9LRU4iXSwianRpIjoiMTNkZjM4ZTAtZDg4Yy0xMWVjLTgyNGYtN2U2YTIxYWZiYzNmIiwiaWF0IjoxNjUzMDg1NjY4fQ.Y0yHy_A9ZP53p7DFfpE3EiQhPo1lAyltkTbqhqzdmVqdZ36PBO7ivXJHyOx3WXnViC1cJqStBZEFDHdTsUtrRyEs3BH91mCBXwHlzwTN9l0JhuozIYK9eMUwCQrtDLN5KBODekjfacORpmxRcJChWIQyX3mF0mqrlpVn5trPSU210FUxm2E_FUjh9Q7u2Az9Ch2PwjPKkdaGsQenUcsaUgVOqIHxGNoYaAqguQ2GqKwnNValF4HJUiBvwsNYrbyjX964qEaspSEtfFzvoT0iT1NYokdTX9jSymRmVdj5fhNiOBoKZjc4mSSvCZqZxJmasJ5CaEe4lUehH8FxsGVAgQ
cyoda.presto.anonymous-username=paul.schleger@cyoda.com

