#
# Copyright (C) 2022 Cyoda Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# suppress inspection "UnusedProperty" for whole file
connector.name=cyoda
cyoda.presto.server.url=http://localhost:8082
cyoda.presto.authentication.type=JWT
cyoda.presto.https-override=true
cyoda.presto.request-page-size=1000
cyoda.presto.user-login-endpoint=/api/auth/login

# Only for dev/test!
# This has a perpetual access token, that can be generated via JwtTokenFactoryTest#createPerpetualAcessToken in cyoda platform project.
# Or run getting started project locally in your IDE, and modify JwtTokenFactory#createAccessJwtToken to return a perpetual access token.
# Do a login via PostMan to grab the access token and refresh token.
cyoda.presto.allow-anonymous-login=true
cyoda.presto.anonymous-user-id=000186c8-0000-1000-8080-808080808080
cyoda.presto.anonymous-token=eyJraWQiOiJiNWE2YTY3Zi1mYWM4LTRlZmUtODk4ZC1mMzRjNWFlOTE0ZjMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwYXVsLnNjaGxlZ2VyQGN5b2RhLmNvbSIsInVzZXJJZCI6IjAwMDE4NmM4LTAwMDAtMTAwMC04MDgwLTgwODA4MDgwODA4MCIsInNjb3BlcyI6WyJST0xFX1VTRVIiLCJBRE1JTiJdLCJpYXQiOjE2NTMwNTk0NTZ9.YZ_5NwTmC4UuQGf24zdd2qzo42wfmLgvy7pZ8iqMV2YB8FRSl-bCAjQzz10mKLFa6GiwE4XpAflroK3X92kJfVZNEkJsNHg8NduADNdDnSBk5WIFSA21AaJzE3YoZPm4oQyT07zBivNFrhITXZhWc_GaBGqN4jG0hK-gT_rOQ098UeWBIlPEjSlNuRjfOgB6oIRs9T6a2mgxYvapGgdRzmmzB6pOUW6lYhYsFnC7F5PT1rIOm7QGcL9PdR5ISXlfliX8YcmeqqOQWjIAIZtxRSh1p1b5uAapTFx4I7CLNC8Il_NmqzYCwEzMgSXphubGVzxgRV_iaJQ1CghvlZKGiQ
cyoda.presto.anonymous-refresh-token=eyJraWQiOiJiNWE2YTY3Zi1mYWM4LTRlZmUtODk4ZC1mMzRjNWFlOTE0ZjMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwYXVsLnNjaGxlZ2VyQGN5b2RhLmNvbSIsInVzZXJJZCI6IjAwMDE4NmM4LTAwMDAtMTAwMC04MDgwLTgwODA4MDgwODA4MCIsInNjb3BlcyI6WyJST0xFX1JFRlJFU0hfVE9LRU4iXSwianRpIjoiMGM4OTE4NTAtZDg0Zi0xMWVjLTk5OTQtYzJjMTc3YjZmNzQ2IiwiaWF0IjoxNjUzMDU5NDU2LCJleHAiOjE2ODQ1OTU0NTZ9.UkH2Xxe41imyEId0cohHtmyMuMS7bvybkXG5cnAxAq8ClyaS5bW52-AuTPGmUfm6mRlKJiFwZah_cpQPJzkyBMfKXcTGFuB_jLlqP6RjYArRrmWcGfaNf2BLdIO7Me5039qDfHWJRHiLlmKWWIadbgb2FRBsAtlEcJPfxBh1teYK6Xg5p3TiMkGzrJqLCXqEfQXuLxGb2o2HXLedDcM9gkbwrxeMxUKS0HYZIRR8LbwU1i0WWaBuKccJt49UOZIFYK33DZUxaVG0FjaMj1Tj5paOWJ6Q9wTJgGIMveab9P06YoW1BWxRuIZQXidLc4OayXksaG9dEAbJKJY70Pjf6g
cyoda.presto.anonymous-username=paul.schleger@cyoda.com
