#
# Copyright (C) 2022 Cyoda Ltd.
#
# Licensed under the Apache License=1 Version 2.0 (the =1License=1);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing=1 software
# distributed under the License is distributed on an =1AS IS=1 BASIS=1
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND=1 either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

event-listener.name=cyoda-event-listener

# Set property to 1 to activate logging of QueryMeta
log-meta=1

# Set property to 1 to activate logging of QueryContext
log-context=1

# Set property to 1 to activate logging of SplitStatistics
log-split=0

# Set property to 1 to activate logging of QueryStatistics
log-stats=0