/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.service.api.beans;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Created by Cyoda on 30/09/16.
 */
@BeanDefinition
public class GroupHeader implements ImmutableBean {
    @JsonProperty
    @PropertyDefinition
    private final String groupValuesJson;

    @JsonProperty
    @PropertyDefinition
    private final String groupValuesJsonBase64;

    @JsonProperty
    @PropertyDefinition
    private final List<String> groupValues;

    @JsonProperty
    @PropertyDefinition
    private final String parentGroupValuesJson;

    @JsonProperty
    @PropertyDefinition
    private final int groupLevel;

    @JsonProperty
    @PropertyDefinition
//    @Deprecated
    private final boolean isNext;

    @JsonProperty
    @PropertyDefinition
    private final boolean leaf;

    //Map key is column name
    @JsonProperty
    @PropertyDefinition
    private final Map<String, Summary> summary;

    @JsonProperty
    @PropertyDefinition
    private final Map<String, Optional> commonGroupValues;
    @JsonProperty
    @PropertyDefinition
    private final Long rowCount;

    @JsonIgnore
    public Set<String> getColumnNames() {
        return summary.keySet();
    }
    // Need this (and a non-final class) because of the Optional. Cyoda is sending null elements.
    @JsonCreator
    public GroupHeader(
            @JsonProperty("groupValuesJson") String groupValuesJson,
            @JsonProperty("groupValuesJsonBase64") String groupValuesJsonBase64,
            @JsonProperty("groupValues")  List<String> groupValues,
            @JsonProperty("parentGroupValuesJson") String parentGroupValuesJson,
            @JsonProperty("groupLevel") int groupLevel,
            @JsonProperty("isNext") boolean isNext,
            @JsonProperty("leaf") boolean leaf,
            @JsonProperty("summary") Map<String, Summary> summary,
            @JsonProperty("commonGroupValues") Map<String, Object> commonGroupValues,
            @JsonProperty("rowCount") Long rowCount) {
        this.groupValuesJson = groupValuesJson;
        this.groupValuesJsonBase64 = groupValuesJsonBase64;
        this.groupValues = groupValues;
        this.parentGroupValuesJson = parentGroupValuesJson;
        this.groupLevel = groupLevel;
        this.isNext = isNext;
        this.leaf = leaf;
        this.summary = summary;
        this.commonGroupValues = commonGroupValues == null ? null : commonGroupValues.entrySet().stream()
                .collect(Collectors.toMap(Map.Entry::getKey, it->Optional.ofNullable(it.getValue())));
        this.rowCount = rowCount;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code GroupHeader}.
     * @return the meta-bean, not null
     */
    public static GroupHeader.Meta meta() {
        return GroupHeader.Meta.INSTANCE;
    }

    static {
        MetaBean.register(GroupHeader.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static GroupHeader.Builder builder() {
        return new GroupHeader.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected GroupHeader(GroupHeader.Builder builder) {
        this.groupValuesJson = builder.groupValuesJson;
        this.groupValuesJsonBase64 = builder.groupValuesJsonBase64;
        this.groupValues = (builder.groupValues != null ? ImmutableList.copyOf(builder.groupValues) : null);
        this.parentGroupValuesJson = builder.parentGroupValuesJson;
        this.groupLevel = builder.groupLevel;
        this.isNext = builder.isNext;
        this.leaf = builder.leaf;
        this.summary = (builder.summary != null ? ImmutableMap.copyOf(builder.summary) : null);
        this.commonGroupValues = (builder.commonGroupValues != null ? ImmutableMap.copyOf(builder.commonGroupValues) : null);
        this.rowCount = builder.rowCount;
    }

    @Override
    public GroupHeader.Meta metaBean() {
        return GroupHeader.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the groupValuesJson.
     * @return the value of the property
     */
    @JsonProperty
    public String getGroupValuesJson() {
        return groupValuesJson;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the groupValuesJsonBase64.
     * @return the value of the property
     */
    @JsonProperty
    public String getGroupValuesJsonBase64() {
        return groupValuesJsonBase64;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the groupValues.
     * @return the value of the property
     */
    @JsonProperty
    public List<String> getGroupValues() {
        return groupValues;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the parentGroupValuesJson.
     * @return the value of the property
     */
    @JsonProperty
    public String getParentGroupValuesJson() {
        return parentGroupValuesJson;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the groupLevel.
     * @return the value of the property
     */
    @JsonProperty
    public int getGroupLevel() {
        return groupLevel;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the isNext.
     * @return the value of the property
     */
    @JsonProperty
    public boolean isIsNext() {
        return isNext;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the leaf.
     * @return the value of the property
     */
    @JsonProperty
    public boolean isLeaf() {
        return leaf;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the summary.
     * @return the value of the property
     */
    @JsonProperty
    public Map<String, Summary> getSummary() {
        return summary;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the commonGroupValues.
     * @return the value of the property
     */
    @JsonProperty
    public Map<String, Optional> getCommonGroupValues() {
        return commonGroupValues;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the rowCount.
     * @return the value of the property
     */
    @JsonProperty
    public Long getRowCount() {
        return rowCount;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            GroupHeader other = (GroupHeader) obj;
            return JodaBeanUtils.equal(groupValuesJson, other.groupValuesJson) &&
                    JodaBeanUtils.equal(groupValuesJsonBase64, other.groupValuesJsonBase64) &&
                    JodaBeanUtils.equal(groupValues, other.groupValues) &&
                    JodaBeanUtils.equal(parentGroupValuesJson, other.parentGroupValuesJson) &&
                    (groupLevel == other.groupLevel) &&
                    (isNext == other.isNext) &&
                    (leaf == other.leaf) &&
                    JodaBeanUtils.equal(summary, other.summary) &&
                    JodaBeanUtils.equal(commonGroupValues, other.commonGroupValues) &&
                    JodaBeanUtils.equal(rowCount, other.rowCount);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(groupValuesJson);
        hash = hash * 31 + JodaBeanUtils.hashCode(groupValuesJsonBase64);
        hash = hash * 31 + JodaBeanUtils.hashCode(groupValues);
        hash = hash * 31 + JodaBeanUtils.hashCode(parentGroupValuesJson);
        hash = hash * 31 + JodaBeanUtils.hashCode(groupLevel);
        hash = hash * 31 + JodaBeanUtils.hashCode(isNext);
        hash = hash * 31 + JodaBeanUtils.hashCode(leaf);
        hash = hash * 31 + JodaBeanUtils.hashCode(summary);
        hash = hash * 31 + JodaBeanUtils.hashCode(commonGroupValues);
        hash = hash * 31 + JodaBeanUtils.hashCode(rowCount);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(352);
        buf.append("GroupHeader{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("groupValuesJson").append('=').append(JodaBeanUtils.toString(groupValuesJson)).append(',').append(' ');
        buf.append("groupValuesJsonBase64").append('=').append(JodaBeanUtils.toString(groupValuesJsonBase64)).append(',').append(' ');
        buf.append("groupValues").append('=').append(JodaBeanUtils.toString(groupValues)).append(',').append(' ');
        buf.append("parentGroupValuesJson").append('=').append(JodaBeanUtils.toString(parentGroupValuesJson)).append(',').append(' ');
        buf.append("groupLevel").append('=').append(JodaBeanUtils.toString(groupLevel)).append(',').append(' ');
        buf.append("isNext").append('=').append(JodaBeanUtils.toString(isNext)).append(',').append(' ');
        buf.append("leaf").append('=').append(JodaBeanUtils.toString(leaf)).append(',').append(' ');
        buf.append("summary").append('=').append(JodaBeanUtils.toString(summary)).append(',').append(' ');
        buf.append("commonGroupValues").append('=').append(JodaBeanUtils.toString(commonGroupValues)).append(',').append(' ');
        buf.append("rowCount").append('=').append(JodaBeanUtils.toString(rowCount)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code GroupHeader}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code groupValuesJson} property.
         */
        private final MetaProperty<String> groupValuesJson = DirectMetaProperty.ofImmutable(
                this, "groupValuesJson", GroupHeader.class, String.class);
        /**
         * The meta-property for the {@code groupValuesJsonBase64} property.
         */
        private final MetaProperty<String> groupValuesJsonBase64 = DirectMetaProperty.ofImmutable(
                this, "groupValuesJsonBase64", GroupHeader.class, String.class);
        /**
         * The meta-property for the {@code groupValues} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<String>> groupValues = DirectMetaProperty.ofImmutable(
                this, "groupValues", GroupHeader.class, (Class) List.class);
        /**
         * The meta-property for the {@code parentGroupValuesJson} property.
         */
        private final MetaProperty<String> parentGroupValuesJson = DirectMetaProperty.ofImmutable(
                this, "parentGroupValuesJson", GroupHeader.class, String.class);
        /**
         * The meta-property for the {@code groupLevel} property.
         */
        private final MetaProperty<Integer> groupLevel = DirectMetaProperty.ofImmutable(
                this, "groupLevel", GroupHeader.class, Integer.TYPE);
        /**
         * The meta-property for the {@code isNext} property.
         */
        private final MetaProperty<Boolean> isNext = DirectMetaProperty.ofImmutable(
                this, "isNext", GroupHeader.class, Boolean.TYPE);
        /**
         * The meta-property for the {@code leaf} property.
         */
        private final MetaProperty<Boolean> leaf = DirectMetaProperty.ofImmutable(
                this, "leaf", GroupHeader.class, Boolean.TYPE);
        /**
         * The meta-property for the {@code summary} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<String, Summary>> summary = DirectMetaProperty.ofImmutable(
                this, "summary", GroupHeader.class, (Class) Map.class);
        /**
         * The meta-property for the {@code commonGroupValues} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<String, Optional>> commonGroupValues = DirectMetaProperty.ofImmutable(
                this, "commonGroupValues", GroupHeader.class, (Class) Map.class);
        /**
         * The meta-property for the {@code rowCount} property.
         */
        private final MetaProperty<Long> rowCount = DirectMetaProperty.ofImmutable(
                this, "rowCount", GroupHeader.class, Long.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "groupValuesJson",
                "groupValuesJsonBase64",
                "groupValues",
                "parentGroupValuesJson",
                "groupLevel",
                "isNext",
                "leaf",
                "summary",
                "commonGroupValues",
                "rowCount");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1061315319:  // groupValuesJson
                    return groupValuesJson;
                case 60324792:  // groupValuesJsonBase64
                    return groupValuesJsonBase64;
                case 827483265:  // groupValues
                    return groupValues;
                case -820927745:  // parentGroupValuesJson
                    return parentGroupValuesJson;
                case 1264512069:  // groupLevel
                    return groupLevel;
                case -1180276931:  // isNext
                    return isNext;
                case 3317598:  // leaf
                    return leaf;
                case -1857640538:  // summary
                    return summary;
                case -1146351210:  // commonGroupValues
                    return commonGroupValues;
                case 17743701:  // rowCount
                    return rowCount;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public GroupHeader.Builder builder() {
            return new GroupHeader.Builder();
        }

        @Override
        public Class<? extends GroupHeader> beanType() {
            return GroupHeader.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code groupValuesJson} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> groupValuesJson() {
            return groupValuesJson;
        }

        /**
         * The meta-property for the {@code groupValuesJsonBase64} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> groupValuesJsonBase64() {
            return groupValuesJsonBase64;
        }

        /**
         * The meta-property for the {@code groupValues} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<String>> groupValues() {
            return groupValues;
        }

        /**
         * The meta-property for the {@code parentGroupValuesJson} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> parentGroupValuesJson() {
            return parentGroupValuesJson;
        }

        /**
         * The meta-property for the {@code groupLevel} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> groupLevel() {
            return groupLevel;
        }

        /**
         * The meta-property for the {@code isNext} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> isNext() {
            return isNext;
        }

        /**
         * The meta-property for the {@code leaf} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> leaf() {
            return leaf;
        }

        /**
         * The meta-property for the {@code summary} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Map<String, Summary>> summary() {
            return summary;
        }

        /**
         * The meta-property for the {@code commonGroupValues} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Map<String, Optional>> commonGroupValues() {
            return commonGroupValues;
        }

        /**
         * The meta-property for the {@code rowCount} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Long> rowCount() {
            return rowCount;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1061315319:  // groupValuesJson
                    return ((GroupHeader) bean).getGroupValuesJson();
                case 60324792:  // groupValuesJsonBase64
                    return ((GroupHeader) bean).getGroupValuesJsonBase64();
                case 827483265:  // groupValues
                    return ((GroupHeader) bean).getGroupValues();
                case -820927745:  // parentGroupValuesJson
                    return ((GroupHeader) bean).getParentGroupValuesJson();
                case 1264512069:  // groupLevel
                    return ((GroupHeader) bean).getGroupLevel();
                case -1180276931:  // isNext
                    return ((GroupHeader) bean).isIsNext();
                case 3317598:  // leaf
                    return ((GroupHeader) bean).isLeaf();
                case -1857640538:  // summary
                    return ((GroupHeader) bean).getSummary();
                case -1146351210:  // commonGroupValues
                    return ((GroupHeader) bean).getCommonGroupValues();
                case 17743701:  // rowCount
                    return ((GroupHeader) bean).getRowCount();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code GroupHeader}.
     */
    public static class Builder extends DirectFieldsBeanBuilder<GroupHeader> {

        private String groupValuesJson;
        private String groupValuesJsonBase64;
        private List<String> groupValues;
        private String parentGroupValuesJson;
        private int groupLevel;
        private boolean isNext;
        private boolean leaf;
        private Map<String, Summary> summary;
        private Map<String, Optional> commonGroupValues;
        private Long rowCount;

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(GroupHeader beanToCopy) {
            this.groupValuesJson = beanToCopy.getGroupValuesJson();
            this.groupValuesJsonBase64 = beanToCopy.getGroupValuesJsonBase64();
            this.groupValues = (beanToCopy.getGroupValues() != null ? ImmutableList.copyOf(beanToCopy.getGroupValues()) : null);
            this.parentGroupValuesJson = beanToCopy.getParentGroupValuesJson();
            this.groupLevel = beanToCopy.getGroupLevel();
            this.isNext = beanToCopy.isIsNext();
            this.leaf = beanToCopy.isLeaf();
            this.summary = (beanToCopy.getSummary() != null ? ImmutableMap.copyOf(beanToCopy.getSummary()) : null);
            this.commonGroupValues = (beanToCopy.getCommonGroupValues() != null ? ImmutableMap.copyOf(beanToCopy.getCommonGroupValues()) : null);
            this.rowCount = beanToCopy.getRowCount();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1061315319:  // groupValuesJson
                    return groupValuesJson;
                case 60324792:  // groupValuesJsonBase64
                    return groupValuesJsonBase64;
                case 827483265:  // groupValues
                    return groupValues;
                case -820927745:  // parentGroupValuesJson
                    return parentGroupValuesJson;
                case 1264512069:  // groupLevel
                    return groupLevel;
                case -1180276931:  // isNext
                    return isNext;
                case 3317598:  // leaf
                    return leaf;
                case -1857640538:  // summary
                    return summary;
                case -1146351210:  // commonGroupValues
                    return commonGroupValues;
                case 17743701:  // rowCount
                    return rowCount;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1061315319:  // groupValuesJson
                    this.groupValuesJson = (String) newValue;
                    break;
                case 60324792:  // groupValuesJsonBase64
                    this.groupValuesJsonBase64 = (String) newValue;
                    break;
                case 827483265:  // groupValues
                    this.groupValues = (List<String>) newValue;
                    break;
                case -820927745:  // parentGroupValuesJson
                    this.parentGroupValuesJson = (String) newValue;
                    break;
                case 1264512069:  // groupLevel
                    this.groupLevel = (Integer) newValue;
                    break;
                case -1180276931:  // isNext
                    this.isNext = (Boolean) newValue;
                    break;
                case 3317598:  // leaf
                    this.leaf = (Boolean) newValue;
                    break;
                case -1857640538:  // summary
                    this.summary = (Map<String, Summary>) newValue;
                    break;
                case -1146351210:  // commonGroupValues
                    this.commonGroupValues = (Map<String, Optional>) newValue;
                    break;
                case 17743701:  // rowCount
                    this.rowCount = (Long) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public GroupHeader build() {
            return new GroupHeader(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the groupValuesJson.
         * @param groupValuesJson  the new value
         * @return this, for chaining, not null
         */
        public Builder groupValuesJson(String groupValuesJson) {
            this.groupValuesJson = groupValuesJson;
            return this;
        }

        /**
         * Sets the groupValuesJsonBase64.
         * @param groupValuesJsonBase64  the new value
         * @return this, for chaining, not null
         */
        public Builder groupValuesJsonBase64(String groupValuesJsonBase64) {
            this.groupValuesJsonBase64 = groupValuesJsonBase64;
            return this;
        }

        /**
         * Sets the groupValues.
         * @param groupValues  the new value
         * @return this, for chaining, not null
         */
        public Builder groupValues(List<String> groupValues) {
            this.groupValues = groupValues;
            return this;
        }

        /**
         * Sets the {@code groupValues} property in the builder
         * from an array of objects.
         * @param groupValues  the new value
         * @return this, for chaining, not null
         */
        public Builder groupValues(String... groupValues) {
            return groupValues(ImmutableList.copyOf(groupValues));
        }

        /**
         * Sets the parentGroupValuesJson.
         * @param parentGroupValuesJson  the new value
         * @return this, for chaining, not null
         */
        public Builder parentGroupValuesJson(String parentGroupValuesJson) {
            this.parentGroupValuesJson = parentGroupValuesJson;
            return this;
        }

        /**
         * Sets the groupLevel.
         * @param groupLevel  the new value
         * @return this, for chaining, not null
         */
        public Builder groupLevel(int groupLevel) {
            this.groupLevel = groupLevel;
            return this;
        }

        /**
         * Sets the isNext.
         * @param isNext  the new value
         * @return this, for chaining, not null
         */
        public Builder isNext(boolean isNext) {
            this.isNext = isNext;
            return this;
        }

        /**
         * Sets the leaf.
         * @param leaf  the new value
         * @return this, for chaining, not null
         */
        public Builder leaf(boolean leaf) {
            this.leaf = leaf;
            return this;
        }

        /**
         * Sets the summary.
         * @param summary  the new value
         * @return this, for chaining, not null
         */
        public Builder summary(Map<String, Summary> summary) {
            this.summary = summary;
            return this;
        }

        /**
         * Sets the commonGroupValues.
         * @param commonGroupValues  the new value
         * @return this, for chaining, not null
         */
        public Builder commonGroupValues(Map<String, Optional> commonGroupValues) {
            this.commonGroupValues = commonGroupValues;
            return this;
        }

        /**
         * Sets the rowCount.
         * @param rowCount  the new value
         * @return this, for chaining, not null
         */
        public Builder rowCount(Long rowCount) {
            this.rowCount = rowCount;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(352);
            buf.append("GroupHeader.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        protected void toString(StringBuilder buf) {
            buf.append("groupValuesJson").append('=').append(JodaBeanUtils.toString(groupValuesJson)).append(',').append(' ');
            buf.append("groupValuesJsonBase64").append('=').append(JodaBeanUtils.toString(groupValuesJsonBase64)).append(',').append(' ');
            buf.append("groupValues").append('=').append(JodaBeanUtils.toString(groupValues)).append(',').append(' ');
            buf.append("parentGroupValuesJson").append('=').append(JodaBeanUtils.toString(parentGroupValuesJson)).append(',').append(' ');
            buf.append("groupLevel").append('=').append(JodaBeanUtils.toString(groupLevel)).append(',').append(' ');
            buf.append("isNext").append('=').append(JodaBeanUtils.toString(isNext)).append(',').append(' ');
            buf.append("leaf").append('=').append(JodaBeanUtils.toString(leaf)).append(',').append(' ');
            buf.append("summary").append('=').append(JodaBeanUtils.toString(summary)).append(',').append(' ');
            buf.append("commonGroupValues").append('=').append(JodaBeanUtils.toString(commonGroupValues)).append(',').append(' ');
            buf.append("rowCount").append('=').append(JodaBeanUtils.toString(rowCount)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
