<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2022 Cyoda Ltd.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  ~
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Remove parent to avoid any checks and packagings -->

    <groupId>com.cyoda.trino</groupId>
    <artifactId>presto-server-runtime</artifactId>
    <version>402</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <sonar.skip>true</sonar.skip>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.trino</groupId>
            <artifactId>trino-server</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-accumulo</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-atop</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-bigquery</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-blackhole</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-cassandra</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-clickhouse</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-delta-lake</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-druid</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-elasticsearch</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-example-http</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-exchange-filesystem</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-geospatial</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-google-sheets</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-hive-hadoop2</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-http-event-listener</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-hudi</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-iceberg</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-jmx</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-kafka</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-kinesis</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-kudu</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-local-file</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-mariadb</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-memory</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-ml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-mongodb</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-mysql</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-oracle</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-password-authenticators</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-phoenix5</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-pinot</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-postgresql</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-prometheus</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-raptor-legacy</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-redis</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-redshift</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-resource-group-managers</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-session-property-managers</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-singlestore</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-sqlserver</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-teradata-functions</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-thrift</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-tpcds</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.trino</groupId>
                    <artifactId>trino-tpch</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-dependency-plugin</artifactId>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>unpack-plugins</id>-->
<!--                        <phase>prepare-package</phase>-->
<!--                        <goals>-->
<!--                            <goal>unpack-dependencies</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <skip>false</skip>-->
<!--                            &lt;!&ndash; take care of all the plugin types &ndash;&gt;-->
<!--                            <includeTypes>zip</includeTypes>-->
<!--                            <includeScope>provided</includeScope>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <id>unpack-launcher</id>-->
<!--                        <phase>prepare-package</phase>-->
<!--                        <goals>-->
<!--                            <goal>unpack-dependencies</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <skip>false</skip>-->
<!--                            <includeArtifactIds>launcher</includeArtifactIds>-->
<!--                            <includeScope>provided</includeScope>-->
<!--                            <outputDirectory>${project.build.directory}/dependency/launcher</outputDirectory>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>bin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <formats>
                                <format>dir</format>
                                <format>tar.gz</format>
                            </formats>
                            <descriptors>
                                <descriptor>src/main/assembly/trino.xml</descriptor>
                            </descriptors>
                            <finalName>trino-server-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>