package com.cyoda.presto.client.treenode.dto;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Date;
import java.util.Map;
import java.util.UUID;
@BeanDefinition
public class EntityContentDto implements Bean {
    @PropertyDefinition
    private UUID id;
    @PropertyDefinition
    private UUID parentId;
    @PropertyDefinition
    private Date lastUpdateDate;
    @PropertyDefinition
    private Map<String, String> contents;

    public EntityContentDto(){}

    public EntityContentDto(UUID id, UUID parentId, Date lastUpdateDate, Map<String, String> contents) {
        this.id = id;
        this.parentId = parentId;
        this.lastUpdateDate = lastUpdateDate;
        this.contents = contents;
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code EntityContentDto}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the id.
     * @return the value of the property
     */
    public UUID getId() {
        return id;
    }

    /**
     * Sets the id.
     * @param id  the new value of the property
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Gets the the {@code id} property.
     * @return the property, not null
     */
    public final Property<UUID> id() {
        return metaBean().id().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the parentId.
     * @return the value of the property
     */
    public UUID getParentId() {
        return parentId;
    }

    /**
     * Sets the parentId.
     * @param parentId  the new value of the property
     */
    public void setParentId(UUID parentId) {
        this.parentId = parentId;
    }

    /**
     * Gets the the {@code parentId} property.
     * @return the property, not null
     */
    public final Property<UUID> parentId() {
        return metaBean().parentId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the lastUpdateDate.
     * @return the value of the property
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the lastUpdateDate.
     * @param lastUpdateDate  the new value of the property
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * Gets the the {@code lastUpdateDate} property.
     * @return the property, not null
     */
    public final Property<Date> lastUpdateDate() {
        return metaBean().lastUpdateDate().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the contents.
     * @return the value of the property
     */
    public Map<String, String> getContents() {
        return contents;
    }

    /**
     * Sets the contents.
     * @param contents  the new value of the property
     */
    public void setContents(Map<String, String> contents) {
        this.contents = contents;
    }

    /**
     * Gets the the {@code contents} property.
     * @return the property, not null
     */
    public final Property<Map<String, String>> contents() {
        return metaBean().contents().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public EntityContentDto clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            EntityContentDto other = (EntityContentDto) obj;
            return JodaBeanUtils.equal(getId(), other.getId()) &&
                    JodaBeanUtils.equal(getParentId(), other.getParentId()) &&
                    JodaBeanUtils.equal(getLastUpdateDate(), other.getLastUpdateDate()) &&
                    JodaBeanUtils.equal(getContents(), other.getContents());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getParentId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getLastUpdateDate());
        hash = hash * 31 + JodaBeanUtils.hashCode(getContents());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(160);
        buf.append("EntityContentDto{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("id").append('=').append(JodaBeanUtils.toString(getId())).append(',').append(' ');
        buf.append("parentId").append('=').append(JodaBeanUtils.toString(getParentId())).append(',').append(' ');
        buf.append("lastUpdateDate").append('=').append(JodaBeanUtils.toString(getLastUpdateDate())).append(',').append(' ');
        buf.append("contents").append('=').append(JodaBeanUtils.toString(getContents())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code EntityContentDto}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code id} property.
         */
        private final MetaProperty<UUID> id = DirectMetaProperty.ofReadWrite(
                this, "id", EntityContentDto.class, UUID.class);
        /**
         * The meta-property for the {@code parentId} property.
         */
        private final MetaProperty<UUID> parentId = DirectMetaProperty.ofReadWrite(
                this, "parentId", EntityContentDto.class, UUID.class);
        /**
         * The meta-property for the {@code lastUpdateDate} property.
         */
        private final MetaProperty<Date> lastUpdateDate = DirectMetaProperty.ofReadWrite(
                this, "lastUpdateDate", EntityContentDto.class, Date.class);
        /**
         * The meta-property for the {@code contents} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Map<String, String>> contents = DirectMetaProperty.ofReadWrite(
                this, "contents", EntityContentDto.class, (Class) Map.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "id",
                "parentId",
                "lastUpdateDate",
                "contents");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return id;
                case 1175162725:  // parentId
                    return parentId;
                case -87311539:  // lastUpdateDate
                    return lastUpdateDate;
                case -567321830:  // contents
                    return contents;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends EntityContentDto> builder() {
            return new DirectBeanBuilder<>(new EntityContentDto());
        }

        @Override
        public Class<? extends EntityContentDto> beanType() {
            return EntityContentDto.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code id} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<UUID> id() {
            return id;
        }

        /**
         * The meta-property for the {@code parentId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<UUID> parentId() {
            return parentId;
        }

        /**
         * The meta-property for the {@code lastUpdateDate} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> lastUpdateDate() {
            return lastUpdateDate;
        }

        /**
         * The meta-property for the {@code contents} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Map<String, String>> contents() {
            return contents;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return ((EntityContentDto) bean).getId();
                case 1175162725:  // parentId
                    return ((EntityContentDto) bean).getParentId();
                case -87311539:  // lastUpdateDate
                    return ((EntityContentDto) bean).getLastUpdateDate();
                case -567321830:  // contents
                    return ((EntityContentDto) bean).getContents();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    ((EntityContentDto) bean).setId((UUID) newValue);
                    return;
                case 1175162725:  // parentId
                    ((EntityContentDto) bean).setParentId((UUID) newValue);
                    return;
                case -87311539:  // lastUpdateDate
                    ((EntityContentDto) bean).setLastUpdateDate((Date) newValue);
                    return;
                case -567321830:  // contents
                    ((EntityContentDto) bean).setContents((Map<String, String>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
