/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.core.reports.columns;

import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;
import java.util.NoSuchElementException;

@BeanDefinition(builderScope = "public")
public class ReportSortColumn implements ImmutableBean {

    @PropertyDefinition(validate = "notNull")
    private final ReportColumn column;

    @PropertyDefinition(validate = "notNull")
    private final boolean reverse;

    public ReportSortColumn(ReportColumn column) {
        this(column, false);
    }

    public ReportSortColumn(ReportColumn column, boolean reverse) {
        this.column = column;
        this.reverse = reverse;
    }

    public String getColumnName() {
        return column.getName();
    }

    public ReportColumn.Type getColumnType() {
        return column.getType();
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ReportSortColumn}.
     * @return the meta-bean, not null
     */
    public static ReportSortColumn.Meta meta() {
        return ReportSortColumn.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ReportSortColumn.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static ReportSortColumn.Builder builder() {
        return new ReportSortColumn.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected ReportSortColumn(ReportSortColumn.Builder builder) {
        JodaBeanUtils.notNull(builder.column, "column");
        JodaBeanUtils.notNull(builder.reverse, "reverse");
        this.column = builder.column;
        this.reverse = builder.reverse;
    }

    @Override
    public ReportSortColumn.Meta metaBean() {
        return ReportSortColumn.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the column.
     * @return the value of the property, not null
     */
    public ReportColumn getColumn() {
        return column;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the reverse.
     * @return the value of the property, not null
     */
    public boolean isReverse() {
        return reverse;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ReportSortColumn other = (ReportSortColumn) obj;
            return JodaBeanUtils.equal(column, other.column) &&
                    (reverse == other.reverse);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(column);
        hash = hash * 31 + JodaBeanUtils.hashCode(reverse);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("ReportSortColumn{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("column").append('=').append(JodaBeanUtils.toString(column)).append(',').append(' ');
        buf.append("reverse").append('=').append(JodaBeanUtils.toString(reverse)).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ReportSortColumn}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code column} property.
         */
        private final MetaProperty<ReportColumn> column = DirectMetaProperty.ofImmutable(
                this, "column", ReportSortColumn.class, ReportColumn.class);
        /**
         * The meta-property for the {@code reverse} property.
         */
        private final MetaProperty<Boolean> reverse = DirectMetaProperty.ofImmutable(
                this, "reverse", ReportSortColumn.class, Boolean.TYPE);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "column",
                "reverse");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1354837162:  // column
                    return column;
                case 1099846370:  // reverse
                    return reverse;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public ReportSortColumn.Builder builder() {
            return new ReportSortColumn.Builder();
        }

        @Override
        public Class<? extends ReportSortColumn> beanType() {
            return ReportSortColumn.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code column} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<ReportColumn> column() {
            return column;
        }

        /**
         * The meta-property for the {@code reverse} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> reverse() {
            return reverse;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1354837162:  // column
                    return ((ReportSortColumn) bean).getColumn();
                case 1099846370:  // reverse
                    return ((ReportSortColumn) bean).isReverse();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code ReportSortColumn}.
     */
    public static class Builder extends DirectFieldsBeanBuilder<ReportSortColumn> {

        private ReportColumn column;
        private boolean reverse;

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(ReportSortColumn beanToCopy) {
            this.column = beanToCopy.getColumn();
            this.reverse = beanToCopy.isReverse();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1354837162:  // column
                    return column;
                case 1099846370:  // reverse
                    return reverse;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -1354837162:  // column
                    this.column = (ReportColumn) newValue;
                    break;
                case 1099846370:  // reverse
                    this.reverse = (Boolean) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public ReportSortColumn build() {
            return new ReportSortColumn(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the column.
         * @param column  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder column(ReportColumn column) {
            JodaBeanUtils.notNull(column, "column");
            this.column = column;
            return this;
        }

        /**
         * Sets the reverse.
         * @param reverse  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder reverse(boolean reverse) {
            JodaBeanUtils.notNull(reverse, "reverse");
            this.reverse = reverse;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(96);
            buf.append("ReportSortColumn.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        protected void toString(StringBuilder buf) {
            buf.append("column").append('=').append(JodaBeanUtils.toString(column)).append(',').append(' ');
            buf.append("reverse").append('=').append(JodaBeanUtils.toString(reverse)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
