/*
 * Copyright (C) 2022 Cyoda Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.cyoda.core.reports.columns;

import com.cyoda.api.deserialization.JodaBeanJacksonDeserializer;
import com.cyoda.api.serialization.JodaBeanJacksonSerializer;
import com.cyoda.core.util.joda.JodaBeansContainer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.List;
import java.util.Map;

/**
 * Container object used only for storing list of ReportColumn, to be able to serialize it with JodaBeanTypeCodec
 */
@JsonDeserialize(using = ReportSummaries.ReportSummariesJacksonDeserializer.class)
@JsonSerialize(using = ReportSummaries.ReportSummariesJacksonSerializer.class)
@BeanDefinition(builderScope = "public")
public class ReportSummaries extends JodaBeansContainer<Map<ReportColumn, List<Function>>> {

    public static class ReportSummariesJacksonDeserializer extends JodaBeanJacksonDeserializer<ReportSummaries> {

        public ReportSummariesJacksonDeserializer() {
            super(ReportSummaries.class);
        }
    }

    public static class ReportSummariesJacksonSerializer extends JodaBeanJacksonSerializer<ReportSummaries> {

        public ReportSummariesJacksonSerializer() {
            super(ReportSummaries.class);
        }
    }

    public ReportSummaries(Map<ReportColumn, List<Function>> summaries) {
        super(summaries);
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ReportSummaries}.
     * @return the meta-bean, not null
     */
    public static ReportSummaries.Meta meta() {
        return ReportSummaries.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ReportSummaries.Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static ReportSummaries.Builder builder() {
        return new ReportSummaries.Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected ReportSummaries(ReportSummaries.Builder builder) {
        super(builder);
    }

    @Override
    public ReportSummaries.Meta metaBean() {
        return ReportSummaries.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public ReportSummaries clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(32);
        buf.append("ReportSummaries{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ReportSummaries}.
     */
    public static class Meta extends JodaBeansContainer.Meta<Map<ReportColumn, List<Function>>> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap());

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public ReportSummaries.Builder builder() {
            return new ReportSummaries.Builder();
        }

        @Override
        public Class<? extends ReportSummaries> beanType() {
            return ReportSummaries.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code ReportSummaries}.
     */
    public static class Builder extends JodaBeansContainer.Builder<Map<ReportColumn, List<Function>>> {

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(ReportSummaries beanToCopy) {
            super(beanToCopy);
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            return super.get(propertyName);
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            super.set(propertyName, newValue);
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public ReportSummaries build() {
            return new ReportSummaries(this);
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(32);
            buf.append("ReportSummaries.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
