/*
 * Copyright (c) 2014 by Cyoda Pty Ltd.
 *   ABN: 13161204771
 *
 *   This software is the confidential and proprietary information
 *   of Cyoda Pty Ltd. ("Confidential Information").  You are
 *   expressly forbidden to publish share or in anyway disseminate
 *   this information.
 */

package com.cyoda.core.conditions;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.joda.beans.ImmutableBean;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;
import java.util.NoSuchElementException;

@BeanDefinition(builderScope = "public")
public abstract class AbstractCondition<T> /*implements Serializable*/ implements ImmutableBean {

    protected static final transient Logger log = LoggerFactory.getLogger(AbstractCondition.class);


    @JsonIgnore
    private boolean withRelatedFieldPresented;

    public AbstractCondition() {
    }

    public abstract boolean isSimple();

    public boolean isWithRelatedFieldPresented() {
        return withRelatedFieldPresented;
    }

    public void setWithRelatedFieldPresented(boolean withRelatedFieldPresented) {
        this.withRelatedFieldPresented = withRelatedFieldPresented;
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code AbstractCondition}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code AbstractCondition}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> Meta<R> metaAbstractCondition(Class<R> cls) {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected AbstractCondition(Builder<T> builder) {
    }

    @SuppressWarnings("unchecked")
    @Override
    public Meta<T> metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public abstract Builder<T> toBuilder();

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return true;
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(32);
        buf.append("AbstractCondition{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code AbstractCondition}.
     * @param <T>  the type
     */
    public static class Meta<T> extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null);

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public boolean isBuildable() {
            return false;
        }

        @Override
        public Builder<T> builder() {
            throw new UnsupportedOperationException("AbstractCondition is an abstract class");
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends AbstractCondition<T>> beanType() {
            return (Class) AbstractCondition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code AbstractCondition}.
     * @param <T>  the type
     */
    public abstract static class Builder<T> extends DirectFieldsBeanBuilder<AbstractCondition<T>> {

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(AbstractCondition<T> beanToCopy) {
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            throw new NoSuchElementException("Unknown property: " + propertyName);
        }

        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            throw new NoSuchElementException("Unknown property: " + propertyName);
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(32);
            buf.append("AbstractCondition.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        protected void toString(StringBuilder buf) {
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
