/*
 * Copyright (c) 2014 by Cyoda Pty Ltd.
 *   ABN: 13161204771
 *
 *   This software is the confidential and proprietary information
 *   of Cyoda Pty Ltd. ("Confidential Information").  You are
 *   expressly forbidden to publish share or in anyway disseminate
 *   this information.
 */

package com.cyoda.core.conditions;

import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Comparator;
import java.util.Map;

@BeanDefinition(hierarchy = "immutable")
public abstract class BetweenRangeCondition<T> extends RangeCondition<T, Comparable> {
    @PropertyDefinition(validate = "notNull")
    protected final Comparable<T> from;

    @PropertyDefinition(validate = "notNull")
    protected final Comparable<T> to;

    protected BetweenRangeCondition(String field, Comparable<T> from, Comparable<T> to, Operation operation, boolean rangeField) {
        super(field, operation, rangeField);
        this.from = from;
        this.to = to;
    }

    @Override
    public String toString() {
        final String sign = getOperationSign();
        return String.format("%s %s %s %s %s", from, sign, getFieldNameForPrint(), sign, to);
    }

    /**
     * Evaluation method for the subclasses to implement.
     *
     * @param from  the lower bound of a range to check.
     * @param to    the upper bound of a range to check.
     * @param value the value to check
     * @param comparator  todo describe
     * @param <S>   the type of range boundaries and value. Must be the same for all of those three.
     * @return true, if the given value belongs to the specified range, false otherwise.
     */
    protected abstract <S> boolean evaluate(S from, S to, Comparable<S> value, Comparator comparator);

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code BetweenRangeCondition}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static BetweenRangeCondition.Meta meta() {
        return BetweenRangeCondition.Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code BetweenRangeCondition}.
     * @param <R>  the bean's generic type
     * @param cls  the bean's generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R> BetweenRangeCondition.Meta<R> metaBetweenRangeCondition(Class<R> cls) {
        return BetweenRangeCondition.Meta.INSTANCE;
    }

    static {
        MetaBean.register(BetweenRangeCondition.Meta.INSTANCE);
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected BetweenRangeCondition(BetweenRangeCondition.Builder<T> builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.from, "from");
        JodaBeanUtils.notNull(builder.to, "to");
        this.from = builder.from;
        this.to = builder.to;
    }

    @SuppressWarnings("unchecked")
    @Override
    public BetweenRangeCondition.Meta<T> metaBean() {
        return BetweenRangeCondition.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the from.
     * @return the value of the property, not null
     */
    public Comparable<T> getFrom() {
        return from;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the to.
     * @return the value of the property, not null
     */
    public Comparable<T> getTo() {
        return to;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public abstract Builder<T> toBuilder();

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            BetweenRangeCondition<?> other = (BetweenRangeCondition<?>) obj;
            return JodaBeanUtils.equal(from, other.from) &&
                    JodaBeanUtils.equal(to, other.to) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(from);
        hash = hash * 31 + JodaBeanUtils.hashCode(to);
        return hash ^ super.hashCode();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code BetweenRangeCondition}.
     * @param <T>  the type
     */
    public static class Meta<T> extends RangeCondition.Meta<T, Comparable> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code from} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Comparable<T>> from = DirectMetaProperty.ofImmutable(
                this, "from", BetweenRangeCondition.class, (Class) Comparable.class);
        /**
         * The meta-property for the {@code to} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<Comparable<T>> to = DirectMetaProperty.ofImmutable(
                this, "to", BetweenRangeCondition.class, (Class) Comparable.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "from",
                "to");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3151786:  // from
                    return from;
                case 3707:  // to
                    return to;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public boolean isBuildable() {
            return false;
        }

        @Override
        public BetweenRangeCondition.Builder<T> builder() {
            throw new UnsupportedOperationException("BetweenRangeCondition is an abstract class");
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends BetweenRangeCondition<T>> beanType() {
            return (Class) BetweenRangeCondition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code from} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Comparable<T>> from() {
            return from;
        }

        /**
         * The meta-property for the {@code to} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Comparable<T>> to() {
            return to;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3151786:  // from
                    return ((BetweenRangeCondition<?>) bean).getFrom();
                case 3707:  // to
                    return ((BetweenRangeCondition<?>) bean).getTo();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code BetweenRangeCondition}.
     * @param <T>  the type
     */
    public abstract static class Builder<T> extends RangeCondition.Builder<T, Comparable> {

        private Comparable<T> from;
        private Comparable<T> to;

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(BetweenRangeCondition<T> beanToCopy) {
            super(beanToCopy);
            this.from = beanToCopy.getFrom();
            this.to = beanToCopy.getTo();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3151786:  // from
                    return from;
                case 3707:  // to
                    return to;
                default:
                    return super.get(propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder<T> set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 3151786:  // from
                    this.from = (Comparable<T>) newValue;
                    break;
                case 3707:  // to
                    this.to = (Comparable<T>) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder<T> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the from.
         * @param from  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T> from(Comparable<T> from) {
            JodaBeanUtils.notNull(from, "from");
            this.from = from;
            return this;
        }

        /**
         * Sets the to.
         * @param to  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T> to(Comparable<T> to) {
            JodaBeanUtils.notNull(to, "to");
            this.to = to;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(96);
            buf.append("BetweenRangeCondition.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("from").append('=').append(JodaBeanUtils.toString(from)).append(',').append(' ');
            buf.append("to").append('=').append(JodaBeanUtils.toString(to)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
