/*
 * Copyright (c) 2014 by Cyoda Pty Ltd.
 *   ABN: 13161204771
 *
 *   This software is the confidential and proprietary information
 *   of Cyoda Pty Ltd. ("Confidential Information").  You are
 *   expressly forbidden to publish share or in anyway disseminate
 *   this information.
 */

package com.cyoda.core.conditions;

import com.cyoda.core.conditions.queryable.Equals;
import com.google.common.base.Joiner;
import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;
import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import javax.validation.constraints.NotNull;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

@BeanDefinition(hierarchy = "immutable")
public class GroupCondition extends AbstractCondition<Object> {

    public enum Operator {
        AND, OR, NOT
    }

    public static final GroupCondition ALL = new GroupCondition(Operator.AND);

    @PropertyDefinition(validate = "notNull")
    private final Operator operator;

    @PropertyDefinition(validate = "notNull")
    private final List<AbstractCondition> conditions;

    public GroupCondition(@NotNull Operator operator, AbstractCondition... conditions) {
        this.operator = operator;
        this.conditions = Arrays.stream(conditions).filter(Objects::nonNull).collect(Collectors.toList());
    }

    public void addCondition(@NotNull AbstractCondition condition) {
        Preconditions.checkNotNull(condition);
        conditions.add(condition);
    }

    public <T extends AbstractCondition> void addConditions(@NotNull Collection<T> conditions) {
        this.conditions.addAll(conditions.stream().filter(Objects::nonNull).collect(Collectors.toList()));
    }

    @Override
    public boolean isSimple() {
        return false;
    }

    @Override
    public String toString() {
        return String.format("{\"%s\": [%s]}", operator, Joiner.on(", ").join(conditions));
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GroupCondition)) return false;

        GroupCondition that = (GroupCondition) o;

        return this.operator == that.operator && this.conditions.equals(that.conditions);
    }

    @Override
    public int hashCode() {
        int result = operator.hashCode();
        result = 31 * result + conditions.hashCode();
        return result;
    }

    public static GroupCondition and(AbstractCondition... conditions) {
        return new GroupCondition(Operator.AND, conditions);
    }

    public static GroupCondition or(AbstractCondition... conditions) {
        return new GroupCondition(Operator.OR, conditions);
    }

    public static GroupCondition and(Collection<AbstractCondition> conditions) {
        return and(conditions.toArray(new AbstractCondition[conditions.size()]));
    }

    public static <T extends AbstractCondition> GroupCondition or(Collection<T> conditions) {
        return or(conditions.toArray(new AbstractCondition[conditions.size()]));
    }

    public static AbstractCondition oneOf(String name, List<String> values) {
        if(values.size() == 1){
            return new Equals(name, values.get(0), false);
        }

        return or(values.stream().map(v -> new Equals(name, v, false)).collect(Collectors.toList()));
    }

    public void addEqualsIfValueNotNull(String name, String value) {
        if (value != null && !value.isEmpty()) {
            conditions.add(new Equals(name, value, false));
        }
    }


    public void addAsOr(String name, List<String> values) {
        if(values == null || values.isEmpty()){
            return;
        }
        if(values.size() == 1){
            conditions.add(new Equals(name, values.get(0), false));
            return;
        }
        final GroupCondition groupCondition = new GroupCondition(Operator.OR);
        for(String value: values){
            groupCondition.addCondition(new Equals(name, value, false));
        }
        conditions.add(groupCondition);
    }

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code GroupCondition}.
     * @return the meta-bean, not null
     */
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected GroupCondition(Builder builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.operator, "operator");
        JodaBeanUtils.notNull(builder.conditions, "conditions");
        this.operator = builder.operator;
        this.conditions = ImmutableList.copyOf(builder.conditions);
    }

    @Override
    public Meta metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the operator.
     * @return the value of the property, not null
     */
    public Operator getOperator() {
        return operator;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the conditions.
     * @return the value of the property, not null
     */
    public List<AbstractCondition> getConditions() {
        return conditions;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public Builder toBuilder() {
        return new Builder(this);
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code GroupCondition}.
     */
    public static class Meta extends AbstractCondition.Meta<Object> {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code operator} property.
         */
        private final MetaProperty<Operator> operator = DirectMetaProperty.ofImmutable(
                this, "operator", GroupCondition.class, Operator.class);
        /**
         * The meta-property for the {@code conditions} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<AbstractCondition>> conditions = DirectMetaProperty.ofImmutable(
                this, "conditions", GroupCondition.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "operator",
                "conditions");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -500553564:  // operator
                    return operator;
                case -930859336:  // conditions
                    return conditions;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public Builder builder() {
            return new Builder();
        }

        @Override
        public Class<? extends GroupCondition> beanType() {
            return GroupCondition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code operator} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Operator> operator() {
            return operator;
        }

        /**
         * The meta-property for the {@code conditions} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<AbstractCondition>> conditions() {
            return conditions;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -500553564:  // operator
                    return ((GroupCondition) bean).getOperator();
                case -930859336:  // conditions
                    return ((GroupCondition) bean).getConditions();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code GroupCondition}.
     */
    public static class Builder extends AbstractCondition.Builder<Object> {

        private Operator operator;
        private List<AbstractCondition> conditions = ImmutableList.of();

        /**
         * Restricted constructor.
         */
        protected Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(GroupCondition beanToCopy) {
            super(beanToCopy);
            this.operator = beanToCopy.getOperator();
            this.conditions = ImmutableList.copyOf(beanToCopy.getConditions());
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case -500553564:  // operator
                    return operator;
                case -930859336:  // conditions
                    return conditions;
                default:
                    return super.get(propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case -500553564:  // operator
                    this.operator = (Operator) newValue;
                    break;
                case -930859336:  // conditions
                    this.conditions = (List<AbstractCondition>) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public GroupCondition build() {
            return new GroupCondition(this);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the operator.
         * @param operator  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder operator(Operator operator) {
            JodaBeanUtils.notNull(operator, "operator");
            this.operator = operator;
            return this;
        }

        /**
         * Sets the conditions.
         * @param conditions  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder conditions(List<AbstractCondition> conditions) {
            JodaBeanUtils.notNull(conditions, "conditions");
            this.conditions = conditions;
            return this;
        }

        /**
         * Sets the {@code conditions} property in the builder
         * from an array of objects.
         * @param conditions  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder conditions(AbstractCondition... conditions) {
            return conditions(ImmutableList.copyOf(conditions));
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(96);
            buf.append("GroupCondition.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("operator").append('=').append(JodaBeanUtils.toString(operator)).append(',').append(' ');
            buf.append("conditions").append('=').append(JodaBeanUtils.toString(conditions)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
