/*
 * Copyright (c) 2014 by Cyoda Pty Ltd.
 *   ABN: 13161204771
 *
 *   This software is the confidential and proprietary information
 *   of Cyoda Pty Ltd. ("Confidential Information").  You are
 *   expressly forbidden to publish share or in anyway disseminate
 *   this information.
 */

package com.cyoda.core.conditions;

import org.joda.beans.Bean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Represents the simple conditions, the ones without nested clauses.
 *
 * @param <T> the type of unit(i.e. entity type).
 * @param <V> the type of value to be checked against the condition. Actually field type
 */
@BeanDefinition(hierarchy = "immutable")
public abstract class SimpleCondition<T, V> extends AbstractCondition<T> {

    @PropertyDefinition(validate = "notNull")
    protected final String fieldName;

    @PropertyDefinition(validate = "notNull")
    protected final Operation operation;

    @PropertyDefinition(validate = "notNull")
    private final AtomicBoolean rangeField;

    protected boolean matchAllElemsInList;

    @ImmutableDefaults
    private static void applyDefaults(Builder builder) {
        builder.rangeField(new AtomicBoolean());
    }

    protected SimpleCondition(String fieldName, Operation operation, boolean rangeField) {
        super();
        this.fieldName = fieldName;
        this.operation = operation;
        //this.rangeField = rangeField;
        this.rangeField = new AtomicBoolean(rangeField);
    }

    @Override
    public boolean isSimple() {
        return true;
    }

    public SimpleCondition setRangeField(boolean rangeField) {
        this.rangeField.set(rangeField);
        return this;
    }

    public SimpleCondition setMatchAllElemsInList(boolean matchAllElemsInList) {
        this.matchAllElemsInList = matchAllElemsInList;
        return this;
    }

    protected boolean isRangeField() {
        return rangeField.get();
    }

    protected String getFieldNameForPrint() {
        String fieldName = getFieldName();
        if (fieldName.length() > 15) {
            fieldName = "..." + fieldName.substring(fieldName.length() - 15);
        }
        return fieldName;
    }

    public abstract SimpleCondition copyWithNewFieldName(String fieldName);

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            SimpleCondition<?, ?> other = (SimpleCondition<?, ?>) obj;
            return JodaBeanUtils.equal(fieldName, other.fieldName) &&
                    JodaBeanUtils.equal(operation, other.operation) &&
                    JodaBeanUtils.equal(isRangeField(), other.isRangeField()) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(fieldName);
        hash = hash * 31 + JodaBeanUtils.hashCode(operation);
        hash = hash * 31 + JodaBeanUtils.hashCode(isRangeField());
        return hash ^ super.hashCode();
    }



    @Override
    public String toString() {
        return "SimpleCondition{" +
            "fieldName='" + fieldName + '\'' +
            ", operation=" + operation +
            ", rangeField=" + isRangeField() +
            '}';
    }
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code SimpleCondition}.
     * @return the meta-bean, not null
     */
    @SuppressWarnings("rawtypes")
    public static Meta meta() {
        return Meta.INSTANCE;
    }

    /**
     * The meta-bean for {@code SimpleCondition}.
     * @param <R>  the first generic type
     * @param <S>  the second generic type
     * @param cls1  the first generic type
     * @param cls2  the second generic type
     * @return the meta-bean, not null
     */
    @SuppressWarnings("unchecked")
    public static <R, S> Meta<R, S> metaSimpleCondition(Class<R> cls1, Class<S> cls2) {
        return Meta.INSTANCE;
    }

    static {
        MetaBean.register(Meta.INSTANCE);
    }

    /**
     * Restricted constructor.
     * @param builder  the builder to copy from, not null
     */
    protected SimpleCondition(Builder<T, V> builder) {
        super(builder);
        JodaBeanUtils.notNull(builder.fieldName, "fieldName");
        JodaBeanUtils.notNull(builder.operation, "operation");
        JodaBeanUtils.notNull(builder.rangeField, "rangeField");
        this.fieldName = builder.fieldName;
        this.operation = builder.operation;
        this.rangeField = builder.rangeField;
    }

    @SuppressWarnings("unchecked")
    @Override
    public Meta<T, V> metaBean() {
        return Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the fieldName.
     * @return the value of the property, not null
     */
    public String getFieldName() {
        return fieldName;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the operation.
     * @return the value of the property, not null
     */
    public Operation getOperation() {
        return operation;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the rangeField.
     * @return the value of the property, not null
     */
    public AtomicBoolean getRangeField() {
        return rangeField;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    @Override
    public abstract Builder<T, V> toBuilder();

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code SimpleCondition}.
     * @param <T>  the type
     * @param <V>  the type
     */
    public static class Meta<T, V> extends AbstractCondition.Meta<T> {
        /**
         * The singleton instance of the meta-bean.
         */
        @SuppressWarnings("rawtypes")
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code fieldName} property.
         */
        private final MetaProperty<String> fieldName = DirectMetaProperty.ofImmutable(
                this, "fieldName", SimpleCondition.class, String.class);
        /**
         * The meta-property for the {@code operation} property.
         */
        private final MetaProperty<Operation> operation = DirectMetaProperty.ofImmutable(
                this, "operation", SimpleCondition.class, Operation.class);
        /**
         * The meta-property for the {@code rangeField} property.
         */
        private final MetaProperty<AtomicBoolean> rangeField = DirectMetaProperty.ofImmutable(
                this, "rangeField", SimpleCondition.class, AtomicBoolean.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "fieldName",
                "operation",
                "rangeField");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    return fieldName;
                case 1662702951:  // operation
                    return operation;
                case -1838500419:  // rangeField
                    return rangeField;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public boolean isBuildable() {
            return false;
        }

        @Override
        public Builder<T, V> builder() {
            throw new UnsupportedOperationException("SimpleCondition is an abstract class");
        }

        @SuppressWarnings({"unchecked", "rawtypes" })
        @Override
        public Class<? extends SimpleCondition<T, V>> beanType() {
            return (Class) SimpleCondition.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code fieldName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> fieldName() {
            return fieldName;
        }

        /**
         * The meta-property for the {@code operation} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Operation> operation() {
            return operation;
        }

        /**
         * The meta-property for the {@code rangeField} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<AtomicBoolean> rangeField() {
            return rangeField;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    return ((SimpleCondition<?, ?>) bean).getFieldName();
                case 1662702951:  // operation
                    return ((SimpleCondition<?, ?>) bean).getOperation();
                case -1838500419:  // rangeField
                    return ((SimpleCondition<?, ?>) bean).getRangeField();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code SimpleCondition}.
     * @param <T>  the type
     * @param <V>  the type
     */
    public abstract static class Builder<T, V> extends AbstractCondition.Builder<T> {

        private String fieldName;
        private Operation operation;
        private AtomicBoolean rangeField;

        /**
         * Restricted constructor.
         */
        protected Builder() {
            applyDefaults(this);
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        protected Builder(SimpleCondition<T, V> beanToCopy) {
            super(beanToCopy);
            this.fieldName = beanToCopy.getFieldName();
            this.operation = beanToCopy.getOperation();
            this.rangeField = beanToCopy.getRangeField();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    return fieldName;
                case 1662702951:  // operation
                    return operation;
                case -1838500419:  // rangeField
                    return rangeField;
                default:
                    return super.get(propertyName);
            }
        }

        @Override
        public Builder<T, V> set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 1265009317:  // fieldName
                    this.fieldName = (String) newValue;
                    break;
                case 1662702951:  // operation
                    this.operation = (Operation) newValue;
                    break;
                case -1838500419:  // rangeField
                    this.rangeField = (AtomicBoolean) newValue;
                    break;
                default:
                    super.set(propertyName, newValue);
                    break;
            }
            return this;
        }

        @Override
        public Builder<T, V> set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the fieldName.
         * @param fieldName  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T, V> fieldName(String fieldName) {
            JodaBeanUtils.notNull(fieldName, "fieldName");
            this.fieldName = fieldName;
            return this;
        }

        /**
         * Sets the operation.
         * @param operation  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T, V> operation(Operation operation) {
            JodaBeanUtils.notNull(operation, "operation");
            this.operation = operation;
            return this;
        }

        /**
         * Sets the rangeField.
         * @param rangeField  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder<T, V> rangeField(AtomicBoolean rangeField) {
            JodaBeanUtils.notNull(rangeField, "rangeField");
            this.rangeField = rangeField;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(128);
            buf.append("SimpleCondition.Builder{");
            int len = buf.length();
            toString(buf);
            if (buf.length() > len) {
                buf.setLength(buf.length() - 2);
            }
            buf.append('}');
            return buf.toString();
        }

        @Override
        protected void toString(StringBuilder buf) {
            super.toString(buf);
            buf.append("fieldName").append('=').append(JodaBeanUtils.toString(fieldName)).append(',').append(' ');
            buf.append("operation").append('=').append(JodaBeanUtils.toString(operation)).append(',').append(' ');
            buf.append("rangeField").append('=').append(JodaBeanUtils.toString(rangeField)).append(',').append(' ');
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
